### ISSUE TITLE
question: minimizing consumption buffering

### ISSUE THREAD

**Issue by marcosrmendezthd** [Shopify/sarama#1072]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.16.0
Kafka Version: 0.9.0.1
Go Version: 1.10

##### Configuration

What configuration values are you using for Sarama and Kafka?

Defaults

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

A question regarding sarama buffering. Say I want to read messages between 2 offsets. I want to minimize the consumption of resources as much as possible; as little buffering of unwanted messages as possible. Any guidelines how best to make this happen with the kafka configuration; channel buffer size, max wait time, max processing time, etc?

**Comment by eapache** [comment]
Since you have explicit topic/partition/offsets in mind in this case, to truly minimize the consumption of resources you can create a `Broker` directly and construct the `FetchRequest`s yourself. That gives you final control and introduces effectively no buffering in the system.

If you want to use the `Consumer` still I would suggest the following config tweaks (see the docs for more details on each key):
- reduce `Net.MaxOpenRequests`
- disable `Metadata.RefreshFrequency`
- strictly limit `Consumer.Fetch.Max` and `Consumer.Fetch.Default`
- strictly limit `ChannelBufferSize`

`Consumer.MaxWaitTime` isn't really relevant unless you're reading "live" topics - since it sounds like you're reading existing static data it makes no difference. `Consumer.MaxProcessingTime` is only really relevant if you're trying to read multiple topics at once to avoid contention. I suppose the way to make it most irrelevant would be to set it to a huge value (minutes or hours).

Hope this helps!

**Comment by marcosrmendezthd** [comment]
perfect. thank you!
