### ISSUE TITLE
Support Kafka client's "auto.offset.reset = throw exception if no offset" setting

### ISSUE THREAD

**Issue by sdotz** [Shopify/sarama#1091]
Feature Request: Support Kafka client's `auto.offset.reset` configuration:
From: https://kafka.apache.org/08/documentation.html
```
What to do when there is no initial offset in Zookeeper or if an offset is out of range:
* smallest : automatically reset the offset to the smallest offset
* largest : automatically reset the offset to the largest offset
* anything else: throw exception to the consumer. If this is set to largest, the consumer may lose some messages when the number of partitions, for the topics it subscribes to, changes on the broker. To prevent data loss during partition addition, set auto.offset.reset to smallest
```

It seems like sarama currently (1.16.0) supports the first two.

**Comment by tinkerware** [comment]
As far as I can see, Sarama supports none of these options; as soon as it sees an out of range offset, it closes the message channel of the partition consumer. For comparison, here's what the Java client does: 

https://github.com/apache/kafka/blob/837f31dd1850b179918f83338b4b4487486b2c58/clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetcher.java#L962

It ignores stale offsets sent from server that it knows have been superseded, then falls back to a new offset based on the value of `auto.offset.reset` consumer config, and if nothing is set then it throws an error back to the client.

**Comment by eapache** [comment]
Closing the message channel is effectively equivalent to throwing an exception, since Go doesn't have exceptions in a meaningful sense. When this happens, the client is able to call `ConsumePartition` with `OffsetNewest` or `OffsetOldest` in order to achieve the behaviour of the other java config options.

> It ignores stale offsets sent from server that it knows have been superseded

This is only valid behaviour when dealing with consumer-groups, which is something that happens in the sarama-cluster library.
