### ISSUE TITLE
getting i/o timeout error when using sarama consumer group

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1192]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.19.0
Kafka Version: v2.0
Go Version: v1.11

##### Problem Description
Getting i/o timeout error from broker when using consumer group.

``` 
Error:          Received unexpected error read tcp <ip>:63133-><ip>:9092: i/o timeout
```

Error is returned from https://github.com/Shopify/sarama/blob/master/broker.go#L592

Note: same kafka cluster is working fine when not using consumer group

**Comment by robertPiro** [comment]
We're experiencing the same problem and cranked up the time outs. It did not resolve the issue. It looks like a connectivity issue, though we are experiencing the same problem on serval deployments which excludes that this is hardware related. We are getting stuck in a loop of rebalances. 

Sarama v1.19.0
Sarama Cluster v2.1.15
Kafka v2.0. 
Go v1.11

Reverting Sarama v1.17 did not help.

**Comment by roxit** [comment]
I experienced perhaps the same problem. One consumer instance using the ConsumerGroup API is fine, but when I tried to start another instance, the other instance got the same error and could not join the group.

Sarama v1.19.0
Kafka 1.1.0
Go v1.10.3

Solved the problem by watching `ConsumerGroupSession.Context().Done()` as well in `ConsumeClaim`.
The comment at https://github.com/Shopify/sarama/blob/v1.19.0/consumer_group.go#L18 is clear enough, but it seems that the example at https://godoc.org/github.com/Shopify/sarama#example-ConsumerGroup does not take rebalancing into consideration.

```
func (h MyHandler) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	var msg SyncMessage
	for {
		select {
		case cMsg := <-claim.Messages():
			err := json.Unmarshal(cMsg.Value, &msg)
			if err != nil {
				return err
			}
			// do something
			sess.MarkMessage(cMsg, "")
		case <-sess.Context().Done():
			return nil
		}
	}
}
```

**Comment by yitian108** [comment]
How I create several consumers with the same consume group via the same kafka client to implement point to point consume?

**Comment by juwell** [comment]
Sarama Version: v1.43.3
Kafka Version: v2.7.2
Go Version: v1.21

Hello everyone, I've also encountered this issue.
However, neither in this issue nor after searching online, has there been a concrete explanation of the cause. I'd like to understand the reason.

There are a few peculiarities about my issue:

1. It only occurs in the production environment and cannot be reproduced in the development environment (also because the cause is unknown, it's difficult to reproduce it in a targeted manner).
2. Other services that use the same logic for initialization and consumption do not encounter this error. Moreover, this service binds about 30 topics to the same consumer group and has 8 pods.
3. This service previously had no issues, but suddenly encountered this problem during a certain release and now encounters this error with a very high probability.

Information that can be provided:

1. There are 3 pods, and these 3 pods have been running stably for at least 5 minutes. Then, a new pod is started, and the error begins to occur.
2. Each pod has a group named aaa that consumes 6 topics, and a corresponding client is created for each topic.
    That is, sarama.NewConsumerGroup() is called for each topic.
3. There are also about 10 other clients consuming 10 different topics with 10 different group names.
4. During startup, multiple consumer groups (sarama.NewConsumerGroup) within a single pod are initialized asynchronously and basically start at the same point in time.
5. In the development environment, increasing the number of pods to 10 and restarting the service multiple times did not result in the error.
6. Each topic has 12 partitions.
7. During the error period, the Kafka server's CPU and memory usage were relatively low, and the network was stable.

Organized relevant logs:

```text
Apr 14, 2025 @ 14:48:08.361 {"saramaLog":"Connected to broker at xxx:9092 (unregistered)\n"}  
Apr 14, 2025 @ 14:48:08.369 {"saramaLog":"client/brokers registered new broker #1 at xxx:9092"}  
Apr 14, 2025 @ 14:48:09.210 {"saramaLog":"client/metadata fetching metadata for all topics from broker xxx:9092\n"}  
Apr 14, 2025 @ 14:48:09.229 {"saramaLog":"client/metadata fetching metadata for [topic] from broker xxx2:9092\n"}  
Apr 14, 2025 @ 14:48:09.239 {"saramaLog":"Connected to broker at xxx:9092 (registered as #1)\n"}
Apr 14, 2025 @ 14:48:39.244 {"saramaLog":"Closed connection to broker xxx:9092\n"}  
Apr 14, 2025 @ 14:48:39.345 ERROR read tcp xxx:46394->xxx:9092: i/o timeout

This is the server-side log:

[2025-04-14 14:48:09,243] INFO [GroupCoordinator 1]: Preparing to rebalance group aaa in state PreparingRebalance with old generation 816 (__consumer_offsets-36) (reason: Adding new member aaa-1ed78c04-d326-450d-906f-4d1c0c57a567 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
```

The groups reporting errors are all aaa, and no errors are reported by other consumer groups. The Sarama Config configuration is as follows, with other configurations set to their default values:

```go
config := sarama.NewConfig()  
config.Consumer.Return.Errors = true  
config.Version = sarama.V2_5_0_0  
config.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategyRange  
config.Consumer.Offsets.Initial = sarama.OffsetOldest  
config.Metadata.Timeout = time.Second * 3
```

From the logs, it can be seen that the connection is closed after 30 seconds. This is likely still during the join phase, and the disconnection likely occurred because the Kafka server did not respond, and Sarama actively closed the connection after the config.Net.ReadTimeout expired.

**But why does the rebalance take more than 30 seconds without a response?**

What I know is that during the join phase, the Kafka server waits for a certain period. If this period exceeds the timeout or all members have joined, it will immediately return the join request and proceed to the sync phase.
This waiting time is configured on the server side as [`group.max.session.timeout.ms`](https://kafka.apache.org/27/documentation.html#brokerconfigs_group.initial.rebalance.delay.ms), with a default value of 3 seconds. My production Kafka also uses 3 seconds.

Thank you!

**Comment by jiuweisu** [comment]
i have the same problem.when start the consumer,i will get the err for a long time ,untill the consumer handle set up.

**Comment by jiuweisu** [comment]
get this:read tcp xxx->xxx: i/o timeout
```go
func (c Consumer) Consume() {
	ctx := context.Background()
	for {
		err := c.consumer.Consume(ctx, []string{c.topic}, &c.handler)
		if err != nil {
			slog.Error("consumer.Consume", "error", err)
			time.Sleep(time.Second * 5)
			continue
		}
	}
}
```

**Comment by jiuweisu** [comment]
i tried like this.it not work for me. i also get this:read tcp xxx->xxx: i/o timeout
```go
func (h *Handler) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for {
		select {
		case <-session.Context().Done():
			slog.Info("Session context cancelled, stopping consumption",
				"name", h.name,
				"partition", claim.Partition(),
				"generationID", session.GenerationID())
			return nil
		case msg:= <-claim.Messages():
			err := h.handle(session, msg)
			if err != nil {
				slog.Error("ConsumeClaim failed", "err", err)
			}
		}
	}
}
```

**Comment by puellanivis** [comment]
It can often be difficult to help anyone diagnose any `i/o timeout` errors, because these happen within the network and/or kernel area, not necessarily in our source code.
