### ISSUE TITLE
Consumer per topic vs multiple topics per consumer

### ISSUE THREAD

**Issue by saraweinberg** [Shopify/sarama#1283]
I have a micro service that should consume from multiple topics.
I wonder what is better to implement:

**1. One consumer that consume from a list of topics**
`cluster, err := cluster.NewConsumer(BROKERS, GropuID, topicNames, config)`
and then I have one go channel with switch case to handle proper logic per topic.
**2.One consumer per topic**
`cluster, err := cluster.NewConsumer(BROKERS, GropuID, topic_1, config)`
`cluster, err := cluster.NewConsumer(BROKERS, GropuID, topic_2, config)`
...
(or NewConsumerFromClient)
With N go channels (one channel per topic...)
?

**Comment by varun06** [comment]
Hey @saraweinberg  it depends on your design and infrastructure. Think in terms of availability and what happens when application goes down. If one consumer is consuming from all the topics, if it goes down, it stops processing for all the topics, but if you have one consumer/topic, then you have more headspace. There is a question about if your machine can handle consuming from a lots of partitions or not. So please think about these things and you will have your answer.
