### ISSUE TITLE
Producer: Add the ability to stream message body from an io.Reader

### ISSUE THREAD

**Issue by JulianMorrison** [Shopify/sarama#130]
It's a bit annoying to have to materialize a message body as an []byte in memory when I have a perfectly good io.Reader that could be used to stream it straight from the origin to Kafka. Particularly, it's bad when the message is large.

**Comment by eapache** [comment]
@wvanbergen if we move to `[]byte` for the producer rather than the encoder interface I guess we should abandon any hope of ever supporting this case?

**Comment by wvanbergen** [comment]
Depends on whether you want this for efficiency (i.e. start sending the message immediately when the first bytes from the `io.Reader` arrive), or just to make the API easier to use. 

The first case is tricky because we need to know we can trust the specified length is correct. The content-length HTTP header is notorious for being not set correctly. And the retry issue is also something that will complicate the implementation, in a part of the code that cnanot really use more complexity. I am not super eager to support this use case for those reasons.

The last case can easily be done using `io.ReadFull`, and providing a helper function that instantiates a `sarama.MessageToSend` with data from the reader, e.g. `sarama.MessageFromReader(...)`

**Comment by eapache** [comment]
Given: "Particularly, it's bad when the message is large." I suspect efficiency.

I'm going to close this, if anybody wants to take a crack at it then feel free to ping.
