### ISSUE TITLE
Consumer group can't consume messages from beginning of the topic

### ISSUE THREAD

**Issue by uynap** [Shopify/sarama#1322]
#### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: Version 1.21.0 (2019-02-24) Latest
Kafka Version: 2.1.0 (Mac installed by brew)
Go Version: go1.11 darwin/amd64

##### Configuration

I use the exactly the code provided here `https://github.com/Shopify/sarama/tree/master/examples/consumergroup` .

##### Problem Description

It seems the `config.Consumer.Offsets.Initial = sarama.OffsetOldest` doesn't take effect when using consumer group.

**Comment by cheesedosa** [comment]
`config.Consumer.Offsets.Initial` only takes effect when offsets are not committed to Kafka/Zookeeper. If the consumer group already has offsets committed, the consumer will resume from the committed offset. Can you test with a new consumer group name (that has not started consuming) and check if this issue still exists?

**Comment by uynap** [comment]
Thank you cheesedose.
When I use a new consumer group name, the issue is gone. Is there anyway in this library that I can use to have the same behaviours like `kafka-console-consumer --bootstrap-server localhost:9092 --topic test --from-beginning` ?

**Comment by cheesedosa** [comment]
`kafka-console-consumer` uses a new consumer group name of the format `console-consumer-<random number>` . You can check the consumer groups active in kafka with `kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list`.

If you want to reproduce the same behaviour as the `console-consumer`, you will have to use a different consumer group name each time. Maybe you can use something like a [uuid](https://github.com/satori/go.uuid) as the group name instead of taking it as command-line argument.

**Comment by uynap** [comment]
It makes sense for me. Thank you again.
