### ISSUE TITLE
how consumergroup works on several process

### ISSUE THREAD

**Issue by huwenbo** [Shopify/sarama#1412]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.22.1
Kafka Version:
Go Version:1.12

##### Configuration

config := sarama.NewConfig()
config.Version = sarama.V1_0_0_0
config.Consumer.Return.Errors = true
config.Consumer.Offsets.Initial = sarama.OffsetNewest

##### Problem Description

Hi gays，
I used consumergroup, and I found only one process can work. 
I test topic has two partitons.
first I start a process and new a consumergroup in process.
But if I start another process want to let consumers which are in the same consumergroup run in  different process. the first process will stop. because the first process in function ConsumeClaim code like:

select {
case msg, ok := <-claim.Messages():
}

ok is false, so I made  process down

just want to know ,how consumergroup works on several process

**Comment by cheesedosa** [comment]
> Hi gays,

:rainbow: 

What you are seeing is correct.
When a new consumer joins the consumer group, every consumer in the group will rebalance.
This means the `ConsumeClaim` loop will exit and `claim.Messages()` will close. That's why you are seeing that `ok` is false.
Did you follow the example mentioned in the doc: https://godoc.org/github.com/Shopify/sarama#example-ConsumerGroup ?
Notice the infinite for loop:
```go
    for {
        topics := []string{"my-topic"}
        handler := exampleConsumerGroupHandler{}

        err := group.Consume(ctx, topics, handler)
        if err != nil {
            panic(err)
        }
    }
```
When a rebalance is triggered, `group.Consume/3` will exit with `err == nil` and the for loop will call `Consume` again in the next iteration. Now the group will start with the new claims. Since, you have 2 partitions, when both processes are running you will see that each process gets 1 partition (after rebalance).

**Comment by huwenbo** [comment]
thanks, now it is running as i wish.

thanks for answer
