### ISSUE TITLE
Unusual / unlicensed dependency in kerberos support

### ISSUE THREAD

**Issue by faec** [Shopify/sarama#1438]
##### Versions

Sarama Version: 1.23.1
Kafka Version: N/A
Go Version: N/A

##### Problem Description

`gssapi_kerberos.go` uses the unusual import `"github.com/jcmturner/gofork/encoding/asn1"` rather than the standard library equivalent `"encoding/asn1"`. This is an undocumented / unlicensed fork of the go code whose repo `README` specifically [says it should not be used](https://github.com/jcmturner/gofork/blob/master/README.md). Did this creep in accidentally or is there a reason the standard library can't be used here? If the latter, could the reasoning and license issues be clarified?

**Comment by bai** [comment]
Thanks for reporting! 

@d1egoaz this might be worth looking into if you'll have time 🙏

**Comment by faec** [comment]
more context, [here](https://github.com/jcmturner/gokrb5/issues/308) is `jcmturner/gokrb5`'s response to the same question (the specific workarounds they need are at the bottom of the `gokrb5` readme... I'm not sure if your use is because of one of those, or is incidental)

**Comment by d1egoaz** [comment]
Thanks @faec, good catch!

I 👀 the `jcmturner/gokrb5` https://github.com/jcmturner/gokrb5#known-issues

and yes, that repo needs to use the `jcmturner/gofork` in order to have some
workarounds about some stuff not implemented or not working as expected.

For the specific case of `github.com/jcmturner/gofork/encoding/asn1` there is no
reason right now to keep using `jcmturner/gofork` as the issue
https://github.com/golang/go/issues/17321 was solved/closed in Dec 15, 2016 and
released in go `1.10`
