### ISSUE TITLE
When putting data on input channel error "panic: send on closed channel"

### ISSUE THREAD

**Issue by belwalkar** [Shopify/sarama#1441]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
I have created producer
```go
func (s *Server) kafkaInit() {
        fmt.Println("Starting kafka init to Connect to broker: ")
        config := sarama.NewConfig()
        config.Producer.RequiredAcks = sarama.WaitForAll
        config.Producer.Retry.Max = 10
        config.Producer.Return.Successes = true
        producer, err := sarama.NewAsyncProducer([]string{"cord-kafka.default.svc.cluster.local:9092"}, config)
        if err != nil {
                panic(err)
        }
        s.dataproducer = producer
        defer func() {
                if err := producer.Close(); err != nil {
                        panic(err)
                }
        }()
}
```
 which runs as a go routine. In another go rouitine when I try to  put message
``` go
s.dataproducer.Input() <- &sarama.ProducerMessage{Topic: importerTopic, Value: sarama.StringEncoder(b)}
```

I get error
panic: send on closed channel

Not sure what is happening. This my first attempt and I am new to this not even sure how to debug this

**Comment by cstrahan** [comment]
@belwalkar If I'm reading your code correctly, it looks like your `defer func() { ... }` is at the end of your `kafkaInit` function (it would help if you formatted your message better so that the code was indented and syntax highlighted). If that's the case, that defer is going to run _immediately_ after you created your `producer` (you may want to review the Go language spec, as it appears that you might be mistaken about what `defer` does), and thus `producer.Close()` is called. Then, later, your goroutine attempt to put a message in the `Input()` channel, but that channel is already closed, because `producer.Close()` closes `Input()` and any other internal channels.

This is all assuming that the code you posted is representative of what you're actually doing in your code base.

**Comment by d1egoaz** [comment]
I've updated the initial issue to format the message.
i'm also closing this as it's not a sarama issue an @cstrahan answer is correct according to the posted code.

**Comment by d1egoaz** [comment]
@belwalkar you can try removing the defer producer close code, so you can test that if the producer is not closed, it should work and produce messages.
Assuming that whatever `s` is (`s.dataproducer`, is still valid when you want to produce the message.

``` go
func (s *Server) kafkaInit() {
        fmt.Println("Starting kafka init to Connect to broker: ")
        config := sarama.NewConfig()
        config.Producer.RequiredAcks = sarama.WaitForAll
        config.Producer.Retry.Max = 10
        config.Producer.Return.Successes = true
        producer, err := sarama.NewAsyncProducer([]string{"cord-kafka.default.svc.cluster.local:9092"}, config)
        if err != nil {
                panic(err)
        }
        s.dataproducer = producer
}
```

**Comment by d1egoaz** [comment]
also, be careful setting `config.Producer.Return.Successes = true` when creating an async producer, as you **will** need to read the Success channel,
https://github.com/Shopify/sarama/blob/d5e4de406e006bd5f69e2dbf41de5c59c260f9f1/config.go#L169-L182


if not sure if need this, leave it with the default value `false`

**Comment by belwalkar** [comment]
Sure thank you very much. That was the issue.

Sorry I was traveling and couldnt reply.
Thanks,
Dinesh
