### ISSUE TITLE
How can I decouple consumption from processing?

### ISSUE THREAD

**Issue by nitin302** [Shopify/sarama#1479]
The Kafka Consumer Java Doc suggests a way to de-couple consumers from the actual processing. 

https://kafka.apache.org/23/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

> 2. Decouple Consumption and Processing
> Another alternative is to have one or more consumer threads that do all data consumption and hands off ConsumerRecords instances to a blocking queue consumed by a pool of processor threads that actually handle the record processing. This option likewise has pros and cons:
> PRO: This option allows independently scaling the number of consumers and processors. This makes it possible to have a single consumer that feeds many processor threads, avoiding any limitation on partitions.
> CON: Guaranteeing order across the processors requires particular care as the threads will execute independently an earlier chunk of data may actually be processed after a later chunk of data just due to the luck of thread execution timing. For processing that has no ordering requirements this is not a problem.
> CON: Manually committing the position becomes harder as it requires that all threads co-ordinate to ensure that processing is complete for that partition.
> There are many possible variations on this approach. For example each processor thread can have its own queue, and the consumer threads can hash into these queues using the TopicPartition to ensure in-order consumption and simplify commit.

I'm trying to implement a similar approach, where-in, I can manually define the number consumers I want to spawn per application process (since, we are always limited by number of partitions, i think its a good to have a static value per process), then async hand off messages to a processing pool. Offset commits are also then async processed using a queue per partition.

for example : https://gist.github.com/RichardHightower/041c2c546e513a3481289ca16fe11cd4

What is a way I can do this with sarama?

**Comment by FrancoisPoinsot** [comment]
If we are talking practical case, I can only point out that kafka scale horizontally using partitions.
Want more parallel processing? increase the number of partitions and consumer.
That is simple and effective.
You might not even need to increase the number of consumers (running applications), since each partitions run in their own goroutine, independently from others.

Now if we are talking fun experiment, what are you ready to throw away exactly?
If you are ready to discard `guarantee of order` and `at least once delivery`, you could just spin up a new goroutine on each new message.
Disable the auto-commit of offset and call the offset commit function yourself when ending processing of a message.
Maybe check you are committing an offset higher that the currently committed one.
With this you would have successfully implemented an hacky version of rabbitMQ using kafka. (I do not recommend)

If you want to keep `at least once delivery`, basically the same but you need to somehow order the call to commitOffset.
You cannot expect offsets to actually be continuous serie of number.
You need to register what offset actually came.
The consumption loop would something like
```
for message := range claim.Messages() {
	offsetManager.RegisterIncomingOffset(message.Offset, message.Partition)
    go func(message Message){
        //TODO some precessing here

        offsetManager.MarkMessage((message.Offset, message.Partition)
    }(message)
}
```

Where you would need to implement `offsetManager` which role is solely to not actually call `session.MarkMessage(message, "")` as soon as `offsetManager.MarkMessage` is called. It should wait for all previous offset registered to be committed first.

I am also most likely forgetting a lot of edge-case, particularly around re-balance and shutting down a consumer.

Once again, the documentation you linked did point out this fact: `Manually committing the position becomes harder`. Yeah, no kidding.

**Comment by nitin302** [comment]
Your option 2 sounds like the approach I want. But yes, offset management does become hard especially with rebalances and synchronising processing threads.
