### ISSUE TITLE
not able to find consumer setting max.poll.interval.ms

### ISSUE THREAD

**Issue by ankitaggarwal1992** [Shopify/sarama#1499]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go     |
| v1.23.1  | 2.2.0  | 1.12.9 |

##### Problem Description
Not able to find any setting to set consumer setting `max.poll.interval.ms` in golag sarama library

**Comment by FrancoisPoinsot** [comment]
Isn't that `Config.Consumer.MaxWaitTime`?

**Comment by ankitaggarwal1992** [comment]
> ~Isn't that `Config.Consumer.MaxWaitTime`?~
> 
> edit: actually after reading a bit, it seems the equivalent is `Consumer.Group.Rebalance.Timeout`
> see : https://kafka.apache.org/documentation/#upgrade_1010_notable

@FrancoisPoinsot thanks for the reply. But I think `Consumer.Group.Rebalance.Timeout` is not same as  `max.poll.interval.ms`. You can see the docs, default value for both of these are different. Also `Consumer.Group.Rebalance.Timeout` means maximum time allowed to rejoin the group once the rebalance has started. But the other value means, that rebalance should not start before that time if poll() is not called

**Comment by FrancoisPoinsot** [comment]
From the description in this article ( http://javierholguera.com/2018/01/01/timeouts-in-kafka-clients-and-kafka-streams/ ), it seem max.poll.interval.ms play 2 roles:

1)
> When the timeout expires, the consumer will stop heart-beating and will leave the consumer group explicitly
 The client self regulate itself and will stop heart-beating when time between 2 polls is longer than this value

For this I am unsure you will find a match in sarama. `Config.Consumer.MaxProcessingTime` kinda seem related, but on single message instead of batch.

2) 
> it is also implicitly timeout for how long a client should be awaited in the event of a rebalance.
This look like `Consumer.Group.Rebalance.Timeout` to me.

The default value does not have to match.
