### ISSUE TITLE
go-metrics inaccurate and opencensus

### ISSUE THREAD

**Issue by sergiosalvatore** [Shopify/sarama#1524]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|v1.21.1 |v2.0.0 | v1.13  |

##### Configuration

n/a

##### Problem Description
go-metrics is problematic for certain types of metrics (like the publishing latency).  For instance, if something happens that causes the producer to deadlock, no messages are being produced and the latency is not updated over time.  Many have now shifted to opencensus for these types of tasks.  Would the maintainers accept a PR that adds opencensus support along side the existing go-metrics?

**Comment by bai** [comment]
👋 See also: https://github.com/Shopify/sarama/issues/1340

**Comment by sergiosalvatore** [comment]
Thank you @bai -- I guess I did not search existing issues well enough.  We'd be happy to help with adding opencensus support when the time comes.

**Comment by slaunay** [comment]
@sergiosalvatore Can you give us more details about the deadlock situation you are talking about?

If your producer is blocked using another library for collecting/generating metrics might not do much more (except if `go-metrics` is the root cause for the deadlock).

I suppose you are talking about `request-latency-in-ms` not getting updated but did you observe other metrics like `record-send-rate`, `outgoing-byte-rate ` or `request-rate`.
