### ISSUE TITLE
best practice with worker pool and consumer group

### ISSUE THREAD

**Issue by vtolstov** [Shopify/sarama#1623]
I have app that uses worker pool with 50 workers. For this workers I'm pull messages from kafka using sarama client with consumer group.
My issue now - when I'm not ack some message in worker, kafka it not redelivery.
As i understand this because autocommit. But after reading docs they sad that if I'm commit message that goes after not commited, kafka thinks that both messages acked
Does this right?
What you recommend to worker pool and consumer group? Preferable to use one connection to kafka from app, and not for each worker. Does it possible?

**Comment by cheesedosa** [comment]
Yes, when you commit a message (offset), all the messages before that message are also acked. It is because zookeeper only stores the one integer (the last one) per partition per consumer group.

If you want ordering and can't lose messages, then you should have 1 partition for each worker. Since you have 50 workers, you should make 50 partitions. You can then balance each of these workers on different nodes using consumer-groups.

**Comment by vtolstov** [comment]
Thanks
