### ISSUE TITLE
How to do a hard commit - group consumer 

### ISSUE THREAD

**Issue by harshana-pickme** [Shopify/sarama#1649]
##### Versions

Version : 1.26.1

| Sarama | Kafka | Go |

##### Problem Description

I have written a Group Consumer with conf.Consumer.Offsets.AutoCommit.Enable = false. I call MarkOffset() once I'm ready to commit.

But MarkOffset does not guarantee that the offset is committed to kafka. But I want to make sure at certain critical points (not every message). Specially when a re-balancing is happening (when consumer message channel is closed for reading). How can I do this?

Thanks
Harshana

**Comment by cheesedosa** [comment]
I don't believe this is possible in sarama. There is no way to sync commit offsets in sarama. You should `MarkOffset()/MarkMessage()` your critical messages and set a very low timeout to `conf.Consumer.Offsets.AutoCommit.Interval`. 

When a rebalance is triggered, the `Cleanup` callback on the consumer group is invoked. You can ensure that your critical messages are committed before returning from the callback.

Maybe @varun06 can help since he knows the internals well. Is there a way for sync commits? This would be useful at my workplace as well.

**Comment by dnwe** [comment]
I don't believe there's currently anything for this. Internally we just track the currently marked offset and mark it dirty until the next commit offset response comes through where we check if we can unset dirty. Theoretically we could additionally track the last know committed offset under a different field and expose that as something you could poll on. Otherwise we'd have to do something similar to the channel-based callback style used in the Producer I guess

**Comment by vikrampunchh** [comment]
Facing same issue.

**Comment by gambrell** [comment]
After calling `consumer.MarkOffset()` call `consumer.CommitOffset()`

```
// CommitOffsets allows to manually commit previously marked offsets. By default there is no
// need to call this function as the consumer will commit offsets automatically
// using the Config.Consumer.Offsets.CommitInterval setting.
//
// Please be aware that calling this function during an internal rebalance cycle may return
// broker errors (e.g. sarama.ErrUnknownMemberId or sarama.ErrIllegalGeneration).
```

**Comment by harshana-pickme** [comment]
Thanks gambrell. Now that we have a Commit() function, we can close this ticket.
