### ISSUE TITLE
Problem with zstd

### ISSUE THREAD

**Issue by Palvaneh** [Shopify/sarama#1698]
##### Versions

| Sarama | Kafka | Go |
|-|-|-|
|v1.26.3|-|v1.13.5|

##### Logs

`go build` result:

<details><summary>logs: CLICK ME</summary>
<p>

```
cannot load github.com/klauspost/compress/zstd: github.com/klauspost/compress@v1.9.8: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.9.8.zip: 403 Forbidden
```

</p>
</details>

##### Problem Description

The `github.com/klauspost/compress@v1.9.8` doesn't have go.mod it that version. So, trying to get `github.com/klauspost/compress/zstd` causes a 404 response, and then Go tries proxy. In your country proxy handles the situation but in some countries/environments, it's not allowed to use Go proxy.

I think updating the `compress` package to latest version which has go.mod fixes issue.

Thanks in advance

**Comment by dnwe** [comment]
@Palvaneh we did previously do a dependecy bump, but had to revert it as it would require all users of Sarama to have switched to using go module supporting Go toolchains so we had to revert it (https://github.com/Shopify/sarama/pull/1630)

However, this shouldn't be a problem as klauspost/compress has no dependencies itself and so your `go build` should be able to just generate a pseudo version.

If you cannot fetch from the public proxy and sumdb due to country restrictions, you can disable it globally in your go env by doing this:
```
go env -w GOPROXY=direct
go env -w GOSUMDB=off
```

Then try re-running your build and hopefully it should be successful

**Comment by Palvaneh** [comment]
Unfortunately didn't help
Thanks again for your reply
