### ISSUE TITLE
Cluster Admin - broker Connected method return false. Is this an issue?

### ISSUE THREAD

**Issue by anjulapaulus** [Shopify/sarama#2222]
##### Versions

| Sarama | Kafka | Go |
|------------|-------|----|
| 1.32.0   | 5.4.6-2.12 |1.16.2  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
       sarama.Logger = log.New(os.Stderr, "[Sarama] ", log.LstdFlags)
	brokers := []string{
		"kafka1:9092",
		"kafka2:9092",
	}

	cfg := sarama.NewConfig()
	cfg.Version = sarama.V2_4_0_0
	admin, err := sarama.NewClusterAdmin(brokers, sarama.NewConfig())
	if err != nil {
		log.Fatal(err)
	}
	brok, _, err := admin.DescribeCluster()
	if err != nil {
		log.Fatal(err)
	}
	for _, b := range brok {
		chck, err := b.Connected()
		if err != nil {
			log.Fatal(err)
		}
		log.Println(chck)
	}
```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
[Sarama] 2022/05/04 18:58:31 Initializing new client
[Sarama] 2022/05/04 18:58:31 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2022/05/04 18:58:31 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2022/05/04 18:58:31 client/metadata fetching metadata for all topics from broker kafka1:9092
[Sarama] 2022/05/04 18:58:31 Connected to broker at kafka1:9092 (unregistered)
[Sarama] 2022/05/04 18:58:31 client/brokers registered new broker #1 at kafka1:9092
[Sarama] 2022/05/04 18:58:31 Successfully initialized new client
[Sarama] 2022/05/04 18:58:31 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2022/05/04 18:58:31 Connected to broker at kafka1:9092 (registered as #1)
```

</p>
</details>

##### Problem Description

I am trying to check whether the brokers are connected but it returns false for the method Connected(). If there an explanation on as why it returns false? I need to write a health check so my initial plan was to check whether the brokers were connected but any other checks I could do?

**Comment by anjulapaulus** [comment]
@dnwe ?

**Comment by dnwe** [comment]
👋🏻 whilst DescribeCluster does return a list of the Broker type, it shouldn't really as that struct is an internal representation of a Broker used by Sarama when it's actively making connections. It seems that it was originally borrowed as a convenience. The only broker information you get back from a Describe are the broker ID, its advertised address and (if applicable) its rack assignment.

If you're trying to do healthchecking, you might be better served by adopting https://github.com/linkedin/cruise-control and/or https://github.com/linkedin/burrow depending on your needs.

If you still want to go ahead and do something with Sarama to try and ascertain health of your remote cluster externally, then I guess you'd create a kafka topic for this purpose, ensure it had enough partitions so that each broker in your cluster had one and then do some message produce+consume roundtripping, striping across each partition.

**Comment by anjulapaulus** [comment]
Thanks @dnwe.
