### ISSUE TITLE
How can i Scale a sarama consumer group in kubernetes

### ISSUE THREAD

**Issue by AnilKumarSahu777** [Shopify/sarama#2238]
| Sarama | Kafka | Go |
|--------|-------|----|
| v1.27.2 |   kafka:kafka-streams:2.7.0| 1.13

I am using the similar code which is there in sarama example code https://github.com/Shopify/sarama/blob/main/consumer_group_example_test.go , when I have two replicas, traffic is going to one of the pod only, but my use case is traffic should be shared between pods, I have given the consumer group name is identical for all the pods

**Comment by dnwe** [comment]
The number of replicas of a given topic-partition are the number of duplicate copies of data that will be stored on different brokers for redundancy.

In order to balance traffic from a topic across multiple consumers in a group, you would want to ensure you have at least as many partitions as consumer clients so they can each be assigned at least one partition within the topic.
