### ISSUE TITLE
Does sarama retry the messages if leadership for a partition changes. 

### ISSUE THREAD

**Issue by lokeshintuit** [Shopify/sarama#229]
Hi Evan,

I am using new sarama and I am getting the following messages on the error channel. 

```
%!(EXTRA sarama.KError=kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.)Error
%!(EXTRA sarama.KError=kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.)Error
```
# 

My question is: Doesn't sarma sends those messages with metadata refresh automatically?  Here, kafka changes leadership from leader 1 to leader 2 and sarama still uses old metadata. 
1. Does saram eventually sends out those messages through flusher? If yes, should we ignore those error messages? If not, shouldn't saram retry those messages. 

THanks,
Lokesh

**Comment by matbhz** [comment]
I see that this thread is quite old, but we're facing similar issues today in our environments here. 
The easiest way we found to reproduce this consistently is if we restart Kafka on our boxes.  When Kafka finally spins up the last messages logged by Sarama are (don't mind the formatting, it's a snippet from Splunk):

```
  1-	 arg4:	 kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.	
  2-	 msg:	 consumer/%s/%d finding new broker	
  3-	 msg:	 client/metadata fetching metadata for %v from broker %s	
  4-	 msg:	 consumer/broker/%d added subscription to %s/%d	
  5-	 msg:	 Connected to broker at %s (registered as #%d)	
  6-	 msg:	 consumer/%s/%d finding new broker	
  7-	 msg:	 client/metadata fetching metadata for %v from broker %s	
  8-	 msg:	 consumer/broker/%d added subscription to %s/%d	
```

Apparently, after knowing that the metatada is out of date it *retries* and finally adds a new subscription, is that right? 

The problem is that after this, no new message are coming from the `consumer.Message()` channel, even though I can see the messages reaching Kafka and the lag starting to build up.

The current solution is to *restart* the application, so it has a fresh connection to Kafka, but that's not ideal. Is there anything I'm missing to force/reconnect to the consumer group?

**Comment by guotie** [comment]
Have this problem solved?

**Comment by eapache** [comment]
Multiple order-preserving retries have been supported in the producer for some time now.

**Comment by ishworg** [comment]
> Also, FWIW, this is not just an issue with leadership changing in case of broker failure. This ALSO happens for any regular kafka operation for managing partitions like re-assignment, controlled shutdown, etc... This means that you go to-do what is a usually safe admin operation and end up causing a production outage because the Sarama producer fails to resiliently send messages as is expected.

Agreed. Regular administrative operation like rolling restart of a single broker should not impact clients from produce/fetch operation.

>   1-	 arg4:	 kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.

We saw this *exact* bug on our sarama clients as well. This issue was on a _critical_ path.

> The current solution is to _restart_ the application, so it has a fresh connection to Kafka, but that's not ideal. Is there anything I'm missing to force/reconnect to the consumer group?

We decided to deprecate the use of sarama library across the board and rolled out diffs to use the Confluent driver. Primarily 1) we needed a better driver 2) transactions
