### ISSUE TITLE
Enabling batching/compression for Sync Producers

### ISSUE THREAD

**Issue by shweta-fourkites** [Shopify/sarama#2343]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.33.0 | 2.2.1 | 1.16  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
config.Consumer.Group.Session.Timeout = 20 * time.Second
config.Consumer.Group.Heartbeat.Interval = 6 * time.Second
config.Consumer.Fetch.Min = 2000
config.Consumer.MaxWaitTime  = 100 * time.Millisecond
config.Consumer.MaxProcessingTime = 15 * time.Second
config.Consumer.Offsets.AutoCommit.Enable = false
config.Consumer.Return.Errors = true
config.Version = sarama.V2_2_1_0

config.Producer.Return.Successes = true
config.Version = sarama.V2_2_1_0
config.Producer.Compression = sarama.CompressionSnappy
config.Producer.Flush.Frequency = 100 * time.Millisecond
config.Producer.Flush.Bytes = 2000
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
2022/09/15 09:25:11.901347 sync_producer.go:53: - DEBUG > message sent to partition 2at offset 47443

2022/09/15 09:25:11.901688 sync_producer.go:53: - DEBUG > message sent to partition 2at offset 47442

```

</p>
</details>

##### Problem Description

We are using SyncProducer in our application. We are trying to enable batching and compression at the producing by setting the below configuration 
config.Producer.Compression = sarama.CompressionSnappy
config.Producer.Flush.Frequency = 100 * time.Millisecond
config.Producer.Flush.Bytes = 2000

The expectation is that this would increase the throughput and reduce lag as we now wont be connecting to kafka to produce each message individually but only once for a batch of messages.

But strangely after introducing batching and compression, we observe a little lag in our producer application. 
**Is batching and compression applicable for Sync producers as well or is it only for Async producers**?

Based on the above configuration, Does the Sync producer wait for 100ms on each message before it can return and produce the next message as Sync producer blocks on acknowledgement? Have we now introduced a lag of 100ms on each message?
From the logs we see message sent to partition message for each individual message, does it mean we produce message one at a time even though batch size is more? Our messages size is less than 1KB per message.

Please clarify! Thanks in advance.

**Comment by shweta-fourkites** [comment]
@dnwe @slaunay

**Comment by shweta-fourkites** [comment]
@dnwe @slaunay Kindly help with the above query

**Comment by dnwe** [comment]
@shweta-fourkites as you may have seen, functionally the Sync producer is just a wrapper around the Async producer https://github.com/Shopify/sarama/blob/619d4ef4d2061b15c438d1e9dfcb3bf5390493d4/sync_producer.go#L60-L76 so certainly compression is equally applicable — it is applied to the data per-message.

As you note, batching is a trickier question because the producer is putting messages on the async producers queue and then waiting for acknowledgement before returning. However, as long as you are using the [SendMessages](https://github.com/Shopify/sarama/blob/619d4ef4d2061b15c438d1e9dfcb3bf5390493d4/sync_producer.go#L124-L147) (plural) api rather than the `SendMessage` (singular) api and you are passing it enough messages to fill a batch then you should be achieving batching — although you'll a) still be awaiting the responses for all of those messages before you start queueing up the next batch and b) batching is per partition leader not per cluster, so throughput still won't be great compared with using the Async producer directly and letting it handle things for you

**Comment by shweta-fourkites** [comment]
@dnwe , Thanks for the clarification.

From my understanding so far, Sync producer sendMessages - will **hit the kafka endpoint once per batch** and collect the responses for all the messages before it returns to the caller. Please correct if i am wrong.

**Comment by dnwe** [comment]
@shweta-fourkites it depends what you mean by "kafka endpoint". All batching is done on a per-broker level and which broker you send messages is arranged on a per-partition level. So when you call `SendMessages` with a slice of messages, if all of those messages are for the same topic partition (tuple) and the total number of messages fits into a batch then yes your SendMessages call would potentially be a single produce request made to a single broker with multiple messages within it and your call would block until that had been acknowledged.

However, as is more likely, you're probably sending messages across a number of partitions (and potentially even a number of topics, each with a number of partitions) then your messages will be directed toward which broker holds leadership for each partition and split across multiple produce requests to multiple brokers in parallel. Still your SendMessages call will block until all of those produce requests have received responses before returning.

**Comment by dnwe** [comment]
Closing as answered
