### ISSUE TITLE
circuit breaker is open loops for ever during re-balance

### ISSUE THREAD

**Issue by joestein** [Shopify/sarama#239]
I setup a test where I am producing 380,000 messages per second from 1 machine to 3 kafka brokers.

When I shutdown (cleanly) one of the brokers this happens

Per Second 387774
&{0xc2096cf240 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc20922c080 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc208a31b00 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209305800 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc20815fc80 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc20847c440 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209bf0780 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc2082cda40 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209a4a6c0 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc208a43d00 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc2096cf280 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc20922c0c0 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc208a31b40 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc208c7e780 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc20815fcc0 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc20847c480 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209bf07c0 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209436a00 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209a4a700 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc209520440 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc208b8fac0 kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.}
&{0xc208b8fb00 circuit breaker is open}
&{0xc208b8fb40 circuit breaker is open}
&{0xc208454580 circuit breaker is open}
&{0xc2084545c0 circuit breaker is open}

..... circuit breaker is open goes on forever and does not recover.

Also please see https://issues.apache.org/jira/browse/KAFKA-1825 not sure where the issue is but something (either on the Sarama side or Kafka side or both (not finger pointing) is not gelling.

**Comment by eapache** [comment]
I'm honestly not sure what else Sarama can do in this situation, or why you would see this bug with the revs you are running but not a few revs prior. The circuit breaker seems to be doing its job properly (in that when part of the cluster gets into a bad state it fails fast so that any remaining partitions don't get backed up).

I'm also not sure what Sarama could be sending to put the cluster in a bad state in the first place, we do rolling restarts under high load all the time and have never seen anything like this.

The gist you posted does not tell me much more than "the broker told us there was a leader election"; presumably we waited a bit and retried and then gave up, which means that perhaps the leader election just happened slowly? There is one case where we generate that error message ourselves, but I can't imagine that's what you're hitting here. I will add a better message around that case anyways but don't expect it to be relevant.

If you have any further information (sarama logs, or a simpler test case that can be run against 0.8.2 final, or...) please let me know, otherwise I'm out of ideas.
