### ISSUE TITLE
Don't get metadata of all topics during startup?

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#274]
Right now, when you open a Sarama client it will retrieve the metadata of all topics in the cluster. Often this is not needed, e.g. when only consuming events from a single topic.

As the number of partitions in a cluster grows, the memory requirements for storing the metadata will go up. Is it worth it to fix this?

**Comment by drdee** [comment]
Yes this sounds like something we should fix and it also doesn't sound too hard so I would like to take a stab at it

**Comment by eapache** [comment]
The memory requirements are not substantial (quite a bit less than one KB per partition I would think) so even storing many thousands of partitions will be cheap (probably <1MB). I'm not sure I really see the motivation for removing this.

There's also the question of what this does to the `backgroundMetadataUpdater` - is it now required to keep track of which topics we're interested in and only update metadata for those topics? That could get complicated. Or do we leave it as is, in which case the "fetch all" happens 10 minutes after creation instead of at creation...

Apart from that however, this is trivial to accomplish; just remove the call to `RefreshAllMetadata()` from `NewClient()` and everything will just work. All the lazy fetch logic is already in place to handle topics created after the current client had done its initial fetch.

**Comment by eapache** [comment]
My previous comment still stands: you would need a truly enormous cluster for this to be worth pursuing at all, and to really get the benefits you'd need a lot more logic in the client.

**Comment by wvanbergen** [comment]
Yeah, a more worthwhile endeavour is preventing the thundering herd of metadata requests after a broker goes down by batching them up.

**Comment by horkhe** [comment]
Once we had an issue with a test topic that had been configured with replication factor 1. When a Kafka node went down, the client started to complain that some partitions did not have leaders and as a result was constantly refreshing metadata even though the test topic was not used by the client.

It is certainly a corner case, but I would vote for client to only care about topics that it is actually using.

**Comment by eapache** [comment]
> as a result was constantly refreshing metadata even though the test topic was not used by the client

It shouldn't be doing that regardless. Every ten minutes when the background refresh happens it might retry a few times, but it shouldn't be refreshing at all constantly.

**Comment by horkhe** [comment]
It could be that every legitimate metadata read resulted in retries because of the not used topic with partitions without a leader.
