### ISSUE TITLE
Single configuration type?

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#308]
After a Twitter conversation: instead of having several different configuration types, we could consolidate them in one.

If we would have a single config struct, The broker/producer/consumer can just grab the relevant settings from it  and ignore the rest. This will make configuration a thing you only have to do once as user, and be done with it. 

``` go
config := sarama.NewClientConfig() // NewConfig? NewKafkaConfig?
config.MaxProduceRetryAttempts = 3
// ...

client := sarama.NewClient(..., config)

// By default, it will grab the config from the client
producer := sarama.NewProducer(client) 

// If you really want to create different producers on the same client with different configs, 
// we could provide an extra method to make that possible:
alternateProducer := sarama.NewProducerWithConfig(client, alternateConfig) 
```

The notable exception here is the offset value setting for the PartitionConsumer, but I feel that should be a function argument instead of a config setting anyway.

@Shopify/kafka Thoughts?

**Comment by wvanbergen** [comment]
@martink @snormore as consumers of the API your input is welcome too!

**Comment by eapache** [comment]
Alternatively, if we do this, in the common case there's no need to expose the client at all:
```go
config := sarama.NewConfig()

// creates an internal client instance, we could expose
// NewProducerFromClient(client, config) if we really wanted to
producer := sarama.NewProducer(config)
```

**Comment by eapache** [comment]
I do like a single `NewConfig()` with a master type, but I also would like to keep the namespacing of the various values, so

```go
config := sarama.NewConfig()
config.Broker.ReadTimeout = 10 * time.Second
config.Producer.RequiredAcks = sarama.WaitForAll
```

etc

**Comment by wvanbergen** [comment]
:+1: to namespacing.

**Comment by eapache** [comment]
The thing I am fighting with now is whether we do

```go
struct Config {
    Client struct {
        // fields
    }
}
```

and make all the subtypes anonymous, or if we leave them as separate named types (like now) and just wrap them in a single master struct. Anonymous feels cleaner, but:
- it means that e.g. the Broker has to carry a *full* config type, and must reference *all* its variables with the full namespace (`b.config.Broker.Foo` instead of `b.config.Foo`)
- it means that we can't construct our default using a literal, and have to assign all the fields manually

**Comment by karlseguin** [comment]
I think this is headed in the right direction. To document my original view:

The documentation states that Producer, Consumer and Client are the core high-level objects. Perhaps I'm wrong, but it really feels like Producer and Consumer are the high level objects, and Client is largely an implementation detail. Client is worth exposing (the more flexibility that's exposed, the better), but I don't think it's necessary to force users to know about Client.

So instead of configuring a client, then configuring a producer, I think you should just configure a producer. And, if Client, as a detail, is something that both Producer and Consumer share, that should be hidden by default (without sacrificing code-reuse, probably via composition).

Something else: while this problem might go away, currently, configuring a client is a little strange to me:
```go
NewClient(id string, addrs []string, config *ClientConfig) (*Client, error)
```
Aren't  `id` and `addrs` configuration values. Why do some some configuration values get promtoed to the constructor, while others sit in a specialized configuration structure? If the idea is that they are mandatory (which is the only reason I can think of), I'd still move them to ClientConfig, but to that constructor:

```go
NewClient(NewClientConfig(id, address)
```

**Comment by wvanbergen** [comment]
I prefer the anonymous struct as well. Constructing the default configuration only happens once, so no need to optimize for that. I actually like the explicitness of having to use the entire config variable name.

Some final thoughts:
- We should probably move all of it to a new file called `config.go`
- `Broker` should be renamed to `Network`, because that's what the options are actually about.
