### ISSUE TITLE
API Changes?

### ISSUE THREAD

**Issue by rberger** [Shopify/sarama#342]
Our apps that use the sarama suddenly stopped working on a recent go get of the sarma library. 
Don't see anything in the Sarama commit log to tell if/when the api changed. 

If its true that the api changed, how do we find out what it is and what version can we pin to delay having to update to the new api?

Or if there is some other thing we're missing in understanding why it suddenly stopped working for us, I would greatly appreciate any insights.
Thanks.

We're seeing things like:

```
bus/bus.go:50: too many arguments in call to sarama.NewClient
bus/bus.go:115: undefined: sarama.NewConsumerConfig
bus/bus.go:116: undefined: sarama.OffsetMethodManual
bus/bus.go:118: too many arguments in call to sarama.NewConsumer
bus/bus.go:127: con.Events undefined (type sarama.Consumer has no field or method Events)
bus/bus.go:153: too many arguments in call to sarama.NewClient
bus/bus.go:160: undefined: sarama.NewProducerConfig
bus/bus.go:165: cannot use cl (type *sarama.Client) as type []string in argument to sarama.NewProducer
bus/bus.go:165: cannot assign sarama.Producer to prod (type *sarama.Producer) in multiple assignment:
	*sarama.Producer is pointer to interface, not interface
bus/bus.go:168: prod.Input undefined (type *sarama.Producer has no field or method Input)
```

**Comment by eapache** [comment]
Yes, sorry about this - as per #302 we're doing a big batch of API changes right now in lead-up to declaring a version 1.0.0 (which will have an API stability guarantee). Things should settle out shortly, and when we do declare v1.0.0 (almost certainly before April) then we're going to document and be much more specific around API stability.

In the meantime, you can pin to the specific SHA you were using via the `godep` tool (https://github.com/tools/godep).

As for what has actually changed in the API, off the top of my head:
- Most of the time people didn't actually use the `Client` except to pass to the `Producer` and `Consumer`, so now those constructors just take a list of addresses directly and create their own internal client object.
- As part of that, we unified the configuration into a single struct and `NewConfig()` constructor, deduplicating and simplifying a lot of options along the way.
- `SimpleProducer` was renamed to `SyncProducer`.
- `Producer` and `Consumer` are now interfaces (not structs) so that they can be mocked for testing.
- `Consumer` now has separate output channels for errors and messages, rather than lumping them together.

If you have any other questions please feel free to ask. We haven't removed any features, just moved things around to simplify the common case, and it's almost over!

Evan

**Comment by rberger** [comment]
Thanks for the response. Do you have a recommendation for what SHA to pin to that is before the Consumer changes? I  presume that was before Rename SimpleProducer to SyncProducer #310?

**Comment by wvanbergen** [comment]
The sha before consumer changes landed: https://github.com/Shopify/sarama/commit/b5282f2da69fbedd61800f97a268c6f897d3f74a

**Comment by eapache** [comment]
v1.0.0 has been tagged and pushed - in the future you can import from `gopkg.in/Shopify/sarama.v1` for guaranteed API stability

**Comment by wvanbergen** [comment]
Also, see the `CHANGELOG` for a high level description of the API changes.

**Comment by potocnyj** [comment]
@wvanbergen FYI - https://github.com/Shopify/sarama/blob/master/CHANGELOG.md says that v1.0.0 is on 4/17, not 3/17

**Comment by wvanbergen** [comment]
whoops, will fix.

**Comment by wvanbergen** [comment]
fixed. Thanks for reporting!
