### ISSUE TITLE
Option: Consumer timeout

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#352]
Instead of always continuing, add a timeout setting that will close a (partition)consumer if no messages have been fetched in the given duration.

**Comment by eapache** [comment]
No objections, just not sure I really see the use case.

**Comment by eapache** [comment]
Like #351, nobody seems to want this and we never had a use case for it.

**Comment by rustjason** [comment]
Hi, @eapache I got a use case for this, bear with me if I am wrong. Since now we have more and more serveless infra like aws lambda. Do you think running a consumer on this kind of serveless infra would be a good idea? Since we don't want to create the machine to run the code and maintain it.  we just need to periodically run this lambda function and it will process the data. in this case, consumer timeout would be a very useful function because they charge the by the runtime.
