### ISSUE TITLE
PartitionConsumer::HighWaterMarkOffset not refreshing client's metadata

### ISSUE THREAD

**Issue by sp-lorenzo-arribas** [Shopify/sarama#460]
Hi, 

I've found that the mentioned method does not take into account the most recent status of a partition, and thus returns an outdated high watermark.

Is this the expected behavior? I find it somewhat inconvenient for certain tasks.

**Comment by wvanbergen** [comment]
This is by design - high water mark offset is sent along with every fetch request; we just expose this value to the end user. Depending on the period between the fetch response arriving and you calling the method, it may be out of date.

It is mainly meant to allow some monitoring on how far you are behind. If you really want an up to date value, use `GetOffset` which will query the broker.
