### ISSUE TITLE
Examples of using AsyncProducer in documentation

### ISSUE THREAD

**Issue by astrekalova** [Shopify/sarama#561]
The documentation of AsyncProducer on https://godoc.org/github.com/Shopify/sarama#AsyncProducer has two examples with Goroutines and Select. Both examples create channels for signals ("// Trap SIGINT to trigger a graceful shutdown"). Why is this necessary? In the example directory there is a example application http_server.go that just uses the close method that is called when the server is closed.

if err := s.DataCollector.Close(); err != nil {
	log.Println("Failed to shut down data collector cleanly", err)
}

I would like to understand why the examples use signals channels while the http_server example does not.
I'm quite new to Golang, so I would appreciate an answer, if though it might be obvious for experiences Gophers.

**Comment by wvanbergen** [comment]
Normally, when the OS sends a signal (e.g. Ctrl+C) to the application, it immediately quits. But we want to run the graceful shutdown to make sure all messages are flushed to Kafka. So a signal handler is added to the application that intercepts the signal, runs the graceful shutdown, and then shuts down the application on its own terms.

In the example application, we do the graceful shutdown in a `defer` of the `main` function: https://github.com/Shopify/sarama/blob/master/examples/http_server/http_server.go#L48-L52. I am actually not sure if that deferred function will run if the application gets interrupted by a signal, so that might be a bug. @eapache do you know the semantics of that?

**Comment by eapache** [comment]
Go does not naturally unwind the stack when an unhandled signal is received, so deferred methods do not get called. If we want the http server example to shutdown gracefully on a signal we will have to change it.
