### ISSUE TITLE
kafka tls

### ISSUE THREAD

**Issue by yqguodataman** [Shopify/sarama#568]
This connection pool can use TLS？Front of my Kafka did with nginx SSL.When I use this gallery ngingx via a TLS connection error.This is error message:FAILED to send message: read tcp x.x.x.x:55529->x.x.x.x:9092: read: connection reset by peer.

This is my code:
cert, err := tls.LoadX509KeyPair("client.pem", "client.key")
        if err != nil {
                fmt.Println("server: loadkeys: %s", err)
        }
        config := &tls.Config{Certificates: []tls.Certificate{cert}, InsecureSkipVerify: true}

        kconfig := kafka.NewConfig()
        //kconfig.Producer.Return.Successes = true
        //kconfig.Producer.Compression = kafka.CompressionSnappy
        kconfig.Net.TLS.Enable = true
        kconfig.Net.TLS.Config = config

        producer, err := kafka.NewSyncProducer([]string{"x.x.x.x:9092"}, kconfig)

**Comment by wvanbergen** [comment]
SSL support was added to support connections over **stunnel**: https://github.com/Shopify/sarama/pull/493.
Maybe nginx does something differently? @uovobw might be able to help here.

**Comment by yqguodataman** [comment]
If don't use nginx,how to configure Kafka TLS? @wvanbergen

**Comment by wvanbergen** [comment]
Apparently with stunnel but I've never done that myself.

**Comment by wvanbergen** [comment]
I see that you are connecting to Kafka on port 9092 (`[]string{"x.x.x.x:9092"}`), but you probably need to connect to the port that does the TLS termination for you (`55529` in your case?)

**Comment by yqguodataman** [comment]
x.x.x.x:9092　is my nginx address port.my nginx configure ssl.Have multiple kafka nginx behind.

**Comment by wvanbergen** [comment]
I'm afraid we can't help you with this. TLS support was contributed and is only known to work with stunnel. If you can get it to work with nginx, please let us know so other people may be able to use what you found.

We don't aim to support every TLS setup under the sun because it's out of the scope of the Kafka protocol. TLS support is in the upcoming Kafka release (0.9), at which point we will make sure sarama will work with that.
