### ISSUE TITLE
ErrNotLeaderForPartition error

### ISSUE THREAD

**Issue by ishare** [Shopify/sarama#595]
We meet ErrNotLeaderForPartition error, and may happen every now and then. I doubt if we need to force to `updateLeader` if this error happens. We use the latest driver commits, and kafka 0.8.2.1, error logs are as below:

`kafka: Failed to produce message to topic CLIENT_LATENCY: kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.`

**Comment by wvanbergen** [comment]
The error tells you that it was sending messages to the wrong broker. This means that the metadata about the cluster on the client side is out of sync. Sarama automatically fetches fresh metadata, and retries when it sees this error. Only after failing for a couple of times this error will be returned to you.

We have seen instances that the cluster will give stale metadata back to the client for a while after a failover has happened. We suspect this is a problem of Zookeeper being out of sync with the Kafka broker. 

Normally, the broker will get back in sync, and will send back the right broker to send messages to back to sarama. If you are noticing that sarama is not trying long enough because you are seeing this error, you can try increasing the number of retries. However, I would also suggest to check if your cluster is having issues, and make sure the connection with zookeeper is healthy.

**Comment by ishare** [comment]
Sorry, I didn't find refresh metadata when meeting ErrNotLeaderForPartition error, only found when meeting this err retry for default 3 times. Does it return to partitionProducer `pp.output == nil`? then the partitionProducer will refresh metadata?
We found when this error happens, some time it will last for about 30 seconds, and it happens every now and then. If samara have this refresh mechanism, it may refresh metadata very quickly.

**Comment by eapache** [comment]
Sarama refreshes 3 times by default and waits only 100ms between each attempt. This may be a bit small, so you can increase it if you want. However if the problem lasts for 30 seconds then something else is wrong, kafka should heal much faster than that when a problem occurs.

**Comment by ishare** [comment]
Will Sarama refresh metadata each time when getting ErrNotLeaderForPartition?

**Comment by eapache** [comment]
Yes. You should be able to see that by setting `sarama.Logger`

**Comment by ForeverSRC** [comment]
@eapache Could you show the code of refreshing metadata when getting ErrNotLeaderForPartition?
