### ISSUE TITLE
Slow Consumer

### ISSUE THREAD

**Issue by kiro** [Shopify/sarama#601]
Hi, we're running sarama client against fairly low volume kafka instance (150 m/s) and we see around 26% cpu usage, when profiling I see this

     800ms 21.68% 21.68%      800ms 21.68%  runtime._ExternalCode
     690ms 18.70% 40.38%      840ms 22.76%  syscall.Syscall
     680ms 18.43% 58.81%      680ms 18.43%  runtime.futex
     450ms 12.20% 71.00%      450ms 12.20%  runtime.usleep
     110ms  2.98% 73.98%      110ms  2.98%  runtime.memmove
      80ms  2.17% 76.15%       80ms  2.17%  runtime.xchg
      70ms  1.90% 78.05%       80ms  2.17%  runtime.mCentral_Grow
      60ms  1.63% 79.67%       80ms  2.17%  runtime.scanobject
      50ms  1.36% 81.03%      170ms  4.61%  runtime.mallocgc
      40ms  1.08% 82.11%       50ms  1.36%  runtime.atomicload

the config is as follows

	kafkaConfig.Producer.RequiredAcks = sarama.WaitForAll
	kafkaConfig.Producer.Return.Errors = true
	kafkaConfig.Producer.Return.Successes = true
	kafkaConfig.Producer.Partitioner = sarama.NewManualPartitioner
	kafkaConfig.Consumer.Return.Errors = true
	kafkaConfig.Net.DialTimeout = 5 * time.Second

can you please advise what might the problem?

**Comment by eapache** [comment]
When you say "slow consumer" do you mean that there is a delay between the message being produced and the message being consumed, or is the concern just that it is using more CPU than you expected?

None of those profile lines look particularly related to Sarama... could it be https://github.com/golang/go/issues/13466?

Please provide more information per https://github.com/Shopify/sarama/blob/master/CONTRIBUTING.md

**Comment by kiro** [comment]
Hi, we're concerned with the high cpu usage, it's seems it's linear to the number of partitions read, when reading 8 partitions is ~3%, 32 ~15%, 64 ~25%

We're using Sarama version Version 1.8.0 (2016-02-01) and Kafka 0.8.2.1

These are the sarama related logs

  INFO consumer/broker/1 added subscription to events/0
  INFO consumer/broker/2 added subscription to events/1
  INFO consumer/broker/1 added subscription to events/2
  INFO consumer/broker/2 added subscription to events/3
  ...
  INFO consumer/broker/1 added subscription to events/60
  INFO consumer/broker/2 added subscription to events/61
  INFO consumer/broker/2 added subscription to events/63
  INFO consumer/broker/1 added subscription to events/62

In kafka server log we see lines like 

  [2016-02-09 12:30:40,138] INFO Closing socket connection to /10.220.104.40. (kafka.network.Processor)

Our code is like this 

	consumer, err := sarama.NewConsumerFromClient(saramaCliemt)
	if err != nil {
		return err
	}

	count := int32(0)
	for i := int32(0); i < 64; i++ {
		partitionConsumer, err := consumer.ConsumePartition(topic, i, sarama.OffsetNewest)
		if err != nil {
			return nil
		}

		go func() {
			for {
				select {
				case <-partitionConsumer.Messages():
					c := atomic.AddInt32(&count, 1)
					if c%1000 == 0 {
						log.Info(c)
					}
				case err := <-partitionConsumer.Errors():
					log.Error(err)
				}
			}
		}()
	}

**Comment by eapache** [comment]
Every partition does add a little bit of overhead - 64 partitions is quite a bit more than you really need for only 150 msg/s in my experience, but it's not totally out of line. Regardless, I wouldn't expect CPU to increase that drastically with partition count.

The profile you posted I still find quite odd - it looks like most of the time is being spent in C code ("ExternalCode"), but sarama doesn't use any, and it doesn't look like your code does either. Are you profiling in a VM? https://groups.google.com/forum/#!msg/golang-nuts/5lxfW3cninU/LemgM21ImmgJ suggests that could lead to bad profile traces due to low-precision timers in the VM kernel. A more useful profile is really the next step here,

In the meantime, there are two config parameters you can try adjusting: `Consumer.Fetch.Min` and `Consumer.MaxWaitTime`. Increasing those should cause the consumer to get messages from the server in larger batches, which should make message processing more efficient especially when there are so many partitions. It will increase the time-to-consume slightly though since it will spend more time waiting for batches to accumulate.

**Comment by kiro** [comment]
Hi, yes it was on a VM. Tried on a real hardware the profile looks similar

     360ms 13.95% 13.95%      360ms 13.95%  runtime.futex
     250ms  9.69% 23.64%      330ms 12.79%  syscall.Syscall
     100ms  3.88% 27.52%      710ms 27.52%  runtime.findrunnable
      90ms  3.49% 31.01%       90ms  3.49%  runtime.xchg
      80ms  3.10% 34.11%       80ms  3.10%  runtime.epollwait
      80ms  3.10% 37.21%       80ms  3.10%  runtime.mapiternext
      70ms  2.71% 39.92%      130ms  5.04%  runtime.runqgrab
      70ms  2.71% 42.64%       70ms  2.71%  runtime.usleep
      60ms  2.33% 44.96%      100ms  3.88%  runtime.mallocgc
      50ms  1.94% 46.90%       50ms  1.94%  runtime._ExternalCode

and this is the graph https://www.dropbox.com/s/n5s0xssygcojxej/pprof001.svg?dl=0

We expect to have peak volumes of 20K messages per second, thus the large number of partitions.

Setting FetchMin=8192 and MaxWaitTime=250ms improved things significantly, reducing cpu usage to 3%. Thanks for your help.

**Comment by eapache** [comment]
Based on what i can make out of that graph, the expensive operations are the syscalls (which are unavoidable, since we are reading from the network) and the goroutine scheduler... we could try to reduce the number of goroutines used somehow, but it's not immediately obvious to me how we'd do that.

Do note that your config tunings may have to be adjusted again when you run against higher volumes of messages.

**Comment by eapache** [comment]
One other thing you might play with to reduce the number of syscalls is to increase the size of the buffer at https://github.com/Shopify/sarama/blob/4ba9bba6adb6697bcec3841e1ecdfecf5227c3b9/utils.go#L105, but it will only have an effect if the responses coming back from the server are regularly larger than the default buffer size (which I think is 4096 bytes in most versions of Go).

**Comment by danield137** [comment]
having issues as well 
https://github.com/Shopify/sarama/issues/726#issuecomment-284888862
