### ISSUE TITLE
How to consume until the end?

### ISSUE THREAD

**Issue by k2xl** [Shopify/sarama#628]
Are there any examples of consuming until reaching the end of a kafka partition? Right now I'm having to implement a timeout (if I don't get a message after X seconds I assume I got to the end)

**Comment by wvanbergen** [comment]
There is no direct way to do this, because Kafka/sarama is built around the concept of never ending streams.

Two ways to accomplish this:
- Timeouts - but this can be tricky when the partition is still receiving new events.
- Get the last offset, start consuming and stop when you have consumed that offset. `Client.GetOffset` can be used to find the latest offset. https://godoc.org/github.com/Shopify/sarama#Client
