### ISSUE TITLE
Low Level Consumer Question

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#631]
i  wrote a kafka consumer driver with erlang. i accomplish the consumer api including  offset_fetch, offset_commit, offset_range and consumer_metadata without any operation to zookeeper.

with my code, after consuming some messages, i can see my consumer group name under zookeeper /consumers path.
but with sarama, i cannot see that. so the day before yesterday, i post this #629 

how to explain this?

**Comment by wvanbergen** [comment]
The low level consumer API will never store anything in Zookeeper, because it doesn't do state tracking. You can either use the offset APIs to deal with tracking state, or the client can implement something on top of the low level consumer API.

So there are two options: 
- Depending on the Kafka version and configuration, the Kafka broker will store the offset information in Zookeeper. So instead of the client communicating with Zookeeper directly, the client communicates with the Kafka broker, which in turns stores this in Zookeeper. 
- The Erlang client (which I don't know) talks to Zookeeper directly.

**Comment by WanliTian** [comment]
the erlang client is written by me. there are no communication between erlang and zookeeper.

and the erlang client && parama using the same kafka cluster

**Comment by wvanbergen** [comment]
In that case, you are most likely using a different version of the CommitOffset API: https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommitRequest. IIRC Sarama uses v1, you may be using v0.

**Comment by WanliTian** [comment]
ok, i got it.
