### ISSUE TITLE
Check config string properties for invalid characters

### ISSUE THREAD

**Issue by bruth** [Shopify/sarama#632]
I filed a bug in the [Kafka JIRA repo](https://issues.apache.org/jira/browse/KAFKA-3417), but it appears that the invalid characters are not being checked for and are causing unexpected downstream errors. When I initially found this using sarama, the client just hung even though I saw an error in the Kafka logs. I am not sure if Kafka is not returning a response or the failure is being ignored.

With a fresh Kafka setup, create the topic and publish a message.

```bash
./kafka-topics --create --topic foo --zookeeper 192.168.99.100:2181 --partitions 1 --replication-factor 1
./kafka-console-producer --topic foo --broker-list 192.168.99.100:9092
hello world
```

Run the code to get the message, an error, or timeout.

```go
package main

import (
	"log"
	"time"

	"github.com/Shopify/sarama"
)

func main() {
	conf := sarama.NewConfig()
	conf.ClientID = "foo:bar"

	con, err := sarama.NewConsumer([]string{"192.168.99.100:9092"}, conf)
	if err != nil {
		log.Fatal(err)
	}
	defer con.Close()

	part, err := con.ConsumePartition("foo", 0, sarama.OffsetOldest)
	if err != nil {
		log.Fatal(err)
	}
	defer part.Close()

	select {
	case <-time.After(time.Second * 2):
		log.Println("timeout")

	case <-part.Messages():
		log.Println("ok")

	case err := <-part.Errors():
		log.Println("error: ", err)

	}
}
```

**Comment by eapache** [comment]
If you enable sarama logging, you will see log messages that explain what's going on. It should be something like the following, repeated (and of course adjusted for your topic, partition, and broker address):
```
2016/03/17 16:40:04 consumer/broker/9092 disconnecting due to error processing FetchRequest: read tcp 192.168.100.1:53294->192.168.100.67:9092: i/o timeout
2016/03/17 16:40:04 kafka: error while consuming test.64/0: read tcp 192.168.100.1:53294->192.168.100.67:9092: i/o timeout
2016/03/17 16:40:06 consumer/test.64/0 finding new broker
```
The consumer's default behaviour for entirely unexpected errors like this one is simply to back off and try again infinitely; this way when the problem is healed (usually it's an actual network error, e.g. cable disconnected) the consumer can just pick up right where it left off.

I will add client-side validation of the `ClientID` field, but I don't think there's anything else we should be doing differently.

**Comment by bruth** [comment]
Great thank you and the reasoning makes sense.
