### ISSUE TITLE
Sarama Batch Size Configuration issue

### ISSUE THREAD

**Issue by safiqueahemad** [Shopify/sarama#636]
Hi All,

I am using Sarama 1.8. I want to use Sarama **batch size** feature.
So, I just enabled batching with some number and time and captured the traffic. I see messages are going in batches. I again changes the configuration but it was still same.

Then finally, disabled the configs still the behavior is same.
One of configurations shown below:
     saramaConfig.Producer.Flush.Frequency = time.Duration(0) // also tried with some +ve value
     saramaConfig.Producer.Flush.Bytes = 0 //also tried with some +ve value
     saramaConfig.Producer.Flush.Messages = 1000 
     saramaConfig.Producer.RequiredAcks = sarama.WaitForLocal

As per my observation, there is no effect of Sarama on batch configuration.
It always send message of fix length (32808 in my case) whether batching is enabled or not.

Please, suggest.

**Comment by eapache** [comment]
Batching is enabled by default and will simply batch as much as is necessary in order to keep up with the number of messages you send. Unless you want more precise latency control or you are getting backed up you shouldn't have to do anything, it should just work.

`Flush.Frequency`, `Flush.Bytes`, and `Flush.Messages` will *not* limit the maximum size of a batch, only the minimum size or frequency. If you are sending messages faster than that, then Sarama will grow the batches as much as is necessary in order to keep up with the speed you are sending.

If you want to limit the maximum you want `Flush.MaxMessages` (this will block if you try to send faster than that). Or, alternatively set the `sarama.MaxRequestSize` global variable.

It's not clear from your description if 32808 is in bytes or in number-of-messages. If it is in bytes, that is possibly TCP or IP fragmentation, and sarama's batches could be bigger or smaller than that. If it is in messages, your requests are quite large and you are probably hitting the maximum request size.

**Comment by safiqueahemad** [comment]
Alright... Thanks a lot for prompt reply.. Its really appreciated...
 
I got your points...

Here, 32808 is the length field in Kafka protocol. The TCP fragment length is 978 almost every Kafka packet(After resembling 32808 comes as whole Kafka packet).

Lets take simple example.
If Flush.Frequency and Flush.Bytes are disabled by setting zero.
**Flush.Messages is set with value 1000.**
If message of 200 bytes are send from sarama async producer then TCP fragment length is 978 almost every Kafka packet(After resembling 32808 comes as length whole Kafka packet)

**Flush.Messages is set with value 1.**
Here sending more number message not just a single
If message of 200 bytes are send from sarama async producer then TCP fragment length is 978 almost every Kafka packet(After resembling 32808 comes as length whole Kafka packet)

If we see here then 32808 is always the length of the Kafka message batch.
What if somebody want to increase this batch size.

**NOTE: MaxRequestSize is set to default to 100 * 1024 * 1024**



Please, suggest.

**Comment by eapache** [comment]
Are you using compression? Are all your messages going to the same topic/partition? When using compression, each partition is limited to `Producer.MaxMessageSize` in *uncompressed* size, which could be the limit you're hitting.

Please enable logging (set `sarama.Logger`) and check the output. Do you see lines like "maximum request accumulated, waiting for space"?

**Comment by safiqueahemad** [comment]
Nope... I am not using compression.
Although, I have enabled sarama.Logger (to stdout) but didn't observe  maximum request accumulated, waiting for space".

**Comment by eapache** [comment]
I do not have any other suggestions based on what you've told me. Could you provide a minimal set of code you are using to reproduce, and perhaps the full sarama logs for a sample run?

**Comment by eapache** [comment]
If you can provide the necessary information I am happy to reopen.
