### ISSUE TITLE
Planned support for new Kafka 0.10 message format

### ISSUE THREAD

**Issue by makkes** [Shopify/sarama#642]
Do you already have plans on supporting the new message format of the upcoming 0.10 release? We're especially interested in using the new timestamps introduced with https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message.

Thanks!

**Comment by wvanbergen** [comment]
No plans as of yet, but we're always interested in contributions.

This may require #617 to be in place first, so we can continue to support older Kafka versions as well. @eapache what do you think?

**Comment by eapache** [comment]
There are two pieces here:
- on-the-wire protocol message support, which we can add at any time and won't conflict with anything
- ability to actually use the new messages in the producer/consumer which depends on #617 to really do properly

Pull requests welcome. I'll probably get around to it eventually otherwise, but it's very low on our list of priorities right now.

**Comment by eapache** [comment]
Support for targeting various kafka versions properly was done in #673 and #676. Support for producer timestamps was done in #678.
