### ISSUE TITLE
should consumer.Close close it's underlying partitionConsumers?

### ISSUE THREAD

**Issue by kanekv** [Shopify/sarama#659]
Right now we should track partitionConsumers and close them separately, can we just close top level Consumer and it will close it's children?

**Comment by eapache** [comment]
I'm not opposed to this in principle, but in cases where you are consuming from multiple partitions it is usually cleaner to call `AsyncClose` on the partitionConsumers so that you have the opportunity to drain the final messages and any possible errors that occur. There isn't an obvious way to do this with the top-level consumer since it can't tell when its children have closed without reading those channels itself, which defeats the purpose.

**Comment by Kane-Sendgrid** [comment]
Can we add AsyncClose to Consumer interface and call underlying partitionConsumers [Async]Close when Consumer.[Async]Close is called?

**Comment by eapache** [comment]
The implementation would be a bit messy I think (we need to ensure that the underlying client got closed only after all partitionConsumers shut down, which probably means hooking into `removeChild`) but I don't see why not.

It's not high on our priority list right now so it will likely be a while before one of us implements it, but we're happy to take pull requests.
