### ISSUE TITLE
it's necessary to add an api of change offset for partitionconsumer

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#689]
##### Problem Description

it's necessary to add an api of change offset for partitionconsumer

**Comment by eapache** [comment]
Can you not just close the partitionconsumer and start a new one with the new offset?

**Comment by WanliTian** [comment]
i think it's convenient to set offset directly

**Comment by eapache** [comment]
It would be convenient initially but it becomes unfortunately complicated because of the asynchronous nature of consuming. There may already be messages buffered for the old offset or requests already in flight to the server, so you would still have to write a bunch of code to handle the old messages, check offset values, and figure out when the first message at the new offset was actually consumed. Shutting down and recreating the partition-consumer is actually fairly inexpensive in most cases, and provides a very clean well-defined break between the old offset and the new one.

**Comment by WanliTian** [comment]
@eapache  you are right, and i will change my code with a different way
