### ISSUE TITLE
Support for Kafka Streams

### ISSUE THREAD

**Issue by boyand** [Shopify/sarama#708]
Hey guys, 

I know you are planning to have a master release that supports 0.10 soon. Are there any plans currently to support the higher level Kafka Streams API:
http://docs.confluent.io/3.0.0/streams/index.html 
http://kafka.apache.org/documentation.html#streamsapi

**Comment by eapache** [comment]
We have no plans to implement the high-level streams API at this point. They're still considered alpha/unstable and add a great deal of client complexity.

Even if somebody implements streams on top of Sarama, I'd probably suggest that it live in a separate package rather than trying to maintain one large repository.
