### ISSUE TITLE
Invalid documentation for NewHashPartitioner

### ISSUE THREAD

**Issue by AlekSi** [Shopify/sarama#717]
Sarama Version: v1.10

https://godoc.org/gopkg.in/Shopify/sarama.v1#NewHashPartitioner says:
> If the message's key is nil, or fails to encode, then a random partition is chosen.

But code [actually](https://github.com/Shopify/sarama/blob/v1.10.0/partitioner.go#L107) returns -1 in case of encoding error, which [results](https://github.com/Shopify/sarama/blob/v1.10.0/async_producer.go#L350) in `ErrInvalidPartition`.

**Comment by eapache** [comment]
It actually returns -1 and the encoding error, so the producer should just pass along the encoding error rather than trying to treat the -1 as a partition (https://github.com/Shopify/sarama/blob/9bb4a68d57ff6f623363aa172f0a8297aa289ba7/async_producer.go#L346-L349). The behaviour makes sense as-is, I will fix the documentation.

Thanks for the report!
