### ISSUE TITLE
producer/broker/xxx state change to [closing] because read tcp xxxx: i/o timeout

### ISSUE THREAD

**Issue by guotie** [Shopify/sarama#739]
##### Versions

Sarama Version: 1.10
Kafka Version: 0.9
Go Version: 1.6

##### Configuration

	config := sarama.NewConfig()
	config.ClientID = "probe-" + fmt.Sprint(pid)
	config.Producer.Retry.Max = 10 // Retry up to 10 times to produce the message
	config.Producer.Compression = sarama.CompressionGZIP

##### Logs

2016/09/01 00:00:37 producer/broker/115 state change to [closing] because read tcp 10.137.148.22:6839->192.168.200.127:9092: i/o timeout
2016/09/01 00:00:37 Closed connection to broker 192.168.200.127:9092
2016/09/01 00:00:37 producer/leader/nd_http_url-03/0 state change to [retrying-1]
2016/09/01 00:00:37 producer/leader/nd_http_url-03/0 abandoning broker 115
2016/09/01 00:00:37 producer/broker/115 shut down
2016/09/01 00:00:37 client/metadata fetching metadata for [nd_http_url-03] from broker 192.168.200.127:9092
2016/09/01 00:00:37 Connected to broker at 192.168.200.127:9092 (registered as #115)
2016/09/01 00:00:37 producer/broker/115 starting up
2016/09/01 00:00:37 producer/broker/115 state change to [open] on nd_http_url-03/0
2016/09/01 00:00:37 producer/leader/nd_http_url-03/0 selected broker 115
2016/09/01 00:00:37 producer/leader/nd_http_url-03/0 state change to [flushing-1]
2016/09/01 00:00:37 producer/leader/nd_http_url-03/0 state change to [normal]
 
##### Problem Description

There are many logs about this， I  don't know why this happens

**Comment by eapache** [comment]
The important bit is "read tcp 10.137.148.22:6839->192.168.200.127:9092: i/o timeout". This means that trying to read the response from the network timed out, either because of the network itself or because the broker is not sending it in time.

You might try changing the `Net.ReadTimeout` configuration value, although it's default is already 30 seconds. Unless you are on a particularly flaky connection that should be more than enough.
