### ISSUE TITLE
Role of offset parameter in ExpectConsumePartition

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#745]
Here's what I —perhaps incorrectly— expected:
1. I would call `ExpectConsumePartition` with an `offset` of 10
2. I would call `ConsumePartition` with the same offset
3. I would `YieldMessage` once
4. The received message from the `Messages` channel would have an `offset` of 10

Instead, no matter the value of offset that I set in line 1 (and 2), the value of the first retrieved message in line 4 is always 1.

Is my expectation wrong?

I looked into the source code and this happens because the offset of the returned message is always `PartitionConsumer.highWatermarkOffset + 1`, and the `highWatermarkOffset` is never explicitly initialized so it's initialized to `nil`. (The only value of the `offset` parameter in line 1 then, is to as act as a check for the `offset` value given in line 2.)

Thank you.

**Comment by eapache** [comment]
Technically your expectation is wrong: kafka is not required to return the same message offset as you give your consumer (for example in compacted topics that offset may not exist and a subsequent one could be returned instead).

However, the code in the mock consumer is also confusing and not particularly helpful, since the high water mark should be different from the consumed offset in the first place, and at least one of those should be initialized to the provided offset as you suggest.

Perhaps the simplest fix might be to let `YieldMessage` respect the offset (if any) of the message parameter it is given?

**Comment by kchristidis** [comment]
> Technically your expectation is wrong: kafka is not required to return the same message offset as you give your consumer (for example in compacted topics that offset may not exist and a subsequent one could be returned instead).

Ah, good point.

> Perhaps the simplest fix might be to let YieldMessage respect the offset (if any) of the message parameter it is given?

Might be the simplest, but it feels brittle, and leaves the developer wondering about the role of the `offset` parameter in the `ExpectConsumerPartition()` and `ConsumePartition()` methods.

Here's a set of truths that we can hopefully agree on. (If I'm wrong, let me know.)

1. The high watermark should generally be different from the consumed offset.
2. The `offset` parameter in `ExpectConsumerPartition()` and `ConsumePartition()` should be set to the same value, and this value is what the next consumed offset should be set to as well.
3. Messages pumped into the system via the `YieldMessage()` call, should be assigned sequence numbers starting from `highWaterMark + 1`.

Point 1 implies we need an additional parameter (`highWatermark int64`) for the `ExpectConsumerPartition()` call. Setting aside how this change will propagate through the rest of the codebase for a moment, let's say this is somewhat "easy".

Point 3 suggests that the current logic for that method is right — cool.

Point 2 is where everything falls apart, because it suggests a change in how the whole `YieldMessage()`, `<-PartitionConsumer.Messages()` logic works in the `mocks` package.

Perhaps, we should require that we have yielded `highWatermark` messages before we can receive from the `PartitionConsumer.Messages()` channel?

This results in a consistent model, but it seems like substantial change in the code logic.

(Note: I do not claim to be an expert in this package, so maybe I'm way off.)

**Comment by eapache** [comment]
> The high watermark should generally be different from the consumed offset.

Yup, more specifically the hwm should always be >= the consumed offset.

> The offset parameter in ExpectConsumerPartition() and ConsumePartition() should be set to the same value

Yes

> and this value is what the next consumed offset should be set to as well.

Only if it's a constant. I suspect the reason most people haven't hit this issue yet is because the majority of use cases just use `OffsetNewest` or else use a library like https://github.com/bsm/sarama-cluster to manage their offsets.

> Messages pumped into the system via the YieldMessage() call, should be assigned sequence numbers starting from highWaterMark + 1.

In theory, however the question is then where do we get the messages to return for offsets between the initial and the highwatermark? E.g. if I start consuming at offset 10 highwatermark 20 I need to also provide an initial batch of 10 messages to make up the difference.

> Point 1 implies we need an additional parameter (highWatermark int64) for the ExpectConsumerPartition() call. Setting aside how this change will propagate through the rest of the codebase for a moment, let's say this is somewhat "easy".

I think so. We can have the highwatermark default to the offset, and provide a setter for unusual cases where they need to be different.

> (Note: I do not claim to be an expert in this package, so maybe I'm way off.)

I think you're on the right track. The trick will be finding a good solution that doesn't totally change the API for existing users.

**Comment by kchristidis** [comment]
Semi-related to this, and a big issue on its own:

When using a mock partition consumer, the lowest/first offset value is 1. In reality though, it's 0, isn't it?

(Again, this is because `YieldMessage()` ignores the offset of the message that is passed to it, and just assigns it the `highWatermark + 1` value, with `highWatermark` initialized to the type's nil value: 0.)
