### ISSUE TITLE
Broker registered at 0.0.0.0 even though NewSyncProducer is given a different IP

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#754]
##### Versions

Sarama Version: af0513c
Kafka Version: 0.9.0.1
Go Version: 1.6 and 1.7

##### Setup

1. Bring up Kafka and ZooKeeper in container A with IP `foo`. ([Sample Dockerfile](https://github.com/kchristidis/docker-kafka/tree/master/kafka) if you're curious.)
2. Bring up sarama-using binary in container B. Point to container A using its IP `foo` and port `9092 ([link](https://gist.github.com/kchristidis/8050ec207dd5b2b7f8cd30d167ba3cc1#file-docker-compose-yml-L13)). 
3. Upon booting up, container B attempts to create a new Producer using the `NewSyncProducer()` call. It passes a slice of strings with `foo:9092` as its only element as the first argument to that function ([link](https://github.com/kchristidis/kafka-orderer/blob/devel/producer.go#L55)). The call returns no error.

##### Expectation

I expect a subsequent `SendMessage()` on this producer to succeed.

##### Reality

sarama:

1. Registers the broker at `0.0.0.0:9092` even though the argument to `NewSyncProducer()` is a different address (`foo:9092`).
2. Attempts to connect to broker `0.0.0.0:9092` to send the message and thus fails.

What am I doing wrong? I **must** be missing something.

I'm attaching a snipper from sarama's log below. Thanks in advance for the help.

```
orderer0_1  | [01:25:31]     producer.go:54: [DEBUG] Connecting to Kafka brokers: [172.17.0.2:9092]
orderer0_1  | [sarama] client.go:107: Initializing new client with addresses: [172.17.0.2:9092]
orderer0_1  | [sarama] client.go:585: client/metadata fetching metadata for all topics from broker 172.17.0.2:9092
orderer0_1  | [sarama] broker.go:141: Connected to broker at 172.17.0.2:9092 (unregistered)
orderer0_1  | [sarama] client.go:384: client/brokers registered new broker #0 at 0.0.0.0:9092
orderer0_1  | [sarama] client.go:151: Successfully initialized new client
orderer0_1  | [01:25:31]     producer.go:62: [DEBUG] Connected to Kafka brokers
orderer0_1  | [sarama] config.go:321: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
orderer0_1  | [01:28:13]    broadcast.go:83: [DEBUG] Prepared block 0 with 1 messages (messages:<data:"genesis" > )
orderer0_1  | [sarama] async_producer.go:583: producer/broker/0 starting up
orderer0_1  | [sarama] async_producer.go:595: producer/broker/0 state change to [open] on test/0
orderer0_1  | [sarama] broker.go:93: Failed to connect to broker 0.0.0.0:9092: dial tcp 0.0.0.0:9092: getsockopt: connection refused
orderer0_1  | [sarama] async_producer.go:761: producer/broker/0 state change to [closing] because dial tcp 0.0.0.0:9092: getsockopt: connection refused
orderer0_1  | [sarama] async_producer.go:457: producer/leader/test/0 state change to [retrying-1]
orderer0_1  | [sarama] async_producer.go:467: producer/leader/test/0 abandoning broker 0
orderer0_1  | [sarama] async_producer.go:662: producer/broker/0 shut down
```

**Comment by eapache** [comment]
The point of confusion here is that the address you pass to Sarama is only used as a seed connection to fetch an initial batch of metadata. The actual producing happens based on the metadata returned from that startup phase.

In this case, per the logs you include, the initial metadata fetch is occuring to the address you specified:
> orderer0_1  | [sarama] client.go:107: Initializing new client with addresses: [172.17.0.2:9092]
> orderer0_1  | [sarama] client.go:585: client/metadata fetching metadata for all topics from broker 172.17.0.2:9092

However the metadata returned from the broker in this step includes that its proper address is 0.0.0.0 and so that's what Sarama tries to use:
> orderer0_1  | [sarama] client.go:384: client/brokers registered new broker #0 at 0.0.0.0:9092

This means that the broker itself is mis-configured to bind or advertise itself on 0.0.0.0 rather than the proper IP address. Take a look at the `host.name`, `listeners`, `advertised.host.name`, and `advertised.listeners` configuration values of your broker.

(It is implemented this way so that for large clusters you only have to provide one or two (potentially load-balanced) addresses during configuration, and Sarama can discover the proper addresses of the entire cluster from this seed connection.)

**Comment by kchristidis** [comment]
Ah, indeed I had the Kafka broker advertise itself on `0.0.0.0`.

Thanks for clearing that up, works like a charm now.
