### ISSUE TITLE
Panic error: interface conversion: interface {} is nil, not chan *sarama.ProducerError

### ISSUE THREAD

**Issue by eaglewu** [Shopify/sarama#785]
##### Versions
*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1548006a8b86e4431c98a96ff029d8c2cfdf7fd3
Kafka Version: 0.8.2.1
Go Version: 1.7.3

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

stderr output:
interface conversion: interface {} is nil, not chan *sarama.ProducerError

##### Problem Description

At  [L123](https://github.com/Shopify/sarama/blob/master/sync_producer.go#L123) the `sp.producer.Successes()` method return type of `chan *ProducerMessage`, but below conversion to` chan *ProducerError ` without and judge.  So boom :(

Why conversion it? can i fix it?

**Comment by eapache** [comment]
I'm not sure I understand and I definitely cannot reproduce.

The code currently ranges over the channel of `ProducerMessage`s, so each iteration `msg` is a `ProducerMessage`. The `SendMessage` and `SendMessages` methods ensure that the metadata field of each `ProducerMessage` is of type `chan *ProducerMessage` so the case should be safe.

Are you doing anything unusual such as modifying the Metadata of messages you send while they are in-flight?

**Comment by eapache** [comment]
Closing as stale, please reopen if more information is available.

**Comment by yangeagle** [comment]
Versions

Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.
Sarama Version: Shopify-sarama-v1.12.0-41-g1b103ff
Kafka Version: kafka_2.11-0.10.0.1
Go Version: 1.8.3
Configuration

What configuration values are you using for Sarama and Kafka?

I use default config， as follows:
producer, err := sarama.NewSyncProducer([]string{p.Address}, nil)

stderr output:
interface conversion: interface {} is nil, not chan *sarama.ProducerError

Problem Description

panic: interface conversion: interface {} is nil, not chan *sarama.ProducerError

goroutine 394 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama.(*syncProducer).handleSuccesses(0xc420316760)
        /home/lanyang/rpmbuild/BUILD/src/github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama/sync_producer.go:147 +0xf7
github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama.(*syncProducer).(github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama.handleSuccesses)-fm()
        /home/lanyang/rpmbuild/BUILD/src/github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama/sync_producer.go:76 +0x2a
github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama.withRecover(0xc420322560)
        /home/lanyang/rpmbuild/BUILD/src/github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama/utils.go:43 +0x43
created by github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama.newSyncProducerFromAsyncProducer
        /home/lanyang/rpmbuild/BUILD/src/github.com/open-falcon/falcon-plus/vendor/github.com/Shopify/sarama/sync_producer.go:76 +0xc7


I create  about 32 sync producers in my program, then use them to send message.

I reproduce this error very easily when my program start.


Please check it.

**Comment by eapache** [comment]
I still cannot reproduce. Can you provide a minimal sample program or test case that causes this error?

**Comment by yangeagle** [comment]
The amount of code is very large.  My application scenario is very complicated.
 I summarize simply as follows:
(1)  32 sync producers  and 32 goroutine in one process. 
(2)  each producer sends message to kafka in each goroutine .
(3) If one goroutine works done , then exit.   a new goroutine is created and continue to use the same producer to send message. The total of goroutines keep 32.

 
But I write this kind of example, and also can't reproduce the error.

If I have more information, I will give you right away.

**Comment by xicl** [comment]
i got this error again 
`panic: interface conversion: interface {} is nil, not chan *sarama.ProducerError
goroutine 71 [running]:
github.com/Shopify/sarama.(*syncProducer).handleSuccesses(0xc8604c1d40)
        /Users/xicl/work/go-code-snippet/src/github.com/Shopify/sarama/sync_producer.go:147 +0x101
github.com/Shopify/sarama.(*syncProducer).(github.com/Shopify/sarama.handleSuccesses)-fm()
        /Users/xicl/work/go-code-snippet/src/github.com/Shopify/sarama/sync_producer.go:76 +0x2a
github.com/Shopify/sarama.withRecover(0xc42018a8c0)
        /Users/xicl/work/go-code-snippet/src/github.com/Shopify/sarama/utils.go:43 +0x43
created by github.com/Shopify/sarama.newSyncProducerFromAsyncProducer
        /Users/xicl/work/go-code-snippet/src/github.com/Shopify/sarama/sync_producer.go:76 +0xc2`
