### ISSUE TITLE
List of errors SyncProducer.SendMessage() can return?

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#798]
Is there a list of the errors the SyncProducer's `SendMessage` method can return?

(The end goal is that if there is one, it will allow me to handle some of them different than others.)

**Comment by eapache** [comment]
`SyncProducer.SendMessage` will return the same set of errors that may be returned from the `AsyncProducer`'s `Errors` channel, except without wrapping them in `ProducerError` structs (since they are already clearly associated with a specific message).

The complete set of errors is not very well-defined, in part because it may include user-defined error types (e.g. returned from a custom `Partitioner` implementation). In broad categories, the errors will either be:
- user-defined errors
- errors from kafka or sarama as defined in the `errors.go` file in this repo
- errors from Go's internal stacks (e.g. networking errors)
