### ISSUE TITLE
ErrInvalidMessage is not only about CRC 

### ISSUE THREAD

**Issue by publysher** [Shopify/sarama#810]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:  d65b3fd46b9f35c68df31b9884aa72dfefe31e04  ( latest )
Kafka Version: N/A
Go Version: N/A

##### Configuration

N/A

##### Logs

N/A

##### Problem Description

`ErrInvalidMessage` (Kafka error 2) returns `"kafka server: Message contents does not match its CRC."` as its error message. However, sending a message without a key to a log-compacted topic also results in error 2. As you can imagine, this was quite confusing. 

Suggested replacement: `"kafka server: Message is invalid."`

**Comment by eapache** [comment]
The original message was taken from the wiki page which has now become https://kafka.apache.org/protocol#protocol_error_codes. That page now says the following about error 2:
> This message has failed its CRC checksum, exceeds the valid size, or is otherwise corrupt.

I suppose a missing key still technically falls into the category of "otherwise corrupt", but the wording makes it sound like an internal error, not something the user has obvious control over. @edenhill should the broker really be returning error 2 in this case, or does the description of the error message need to be updated?

**Comment by gmanolache** [comment]
Encountered this issue also.

The problem was the payload size that was bigger than the kafka max size flag: `message.max.bytes: 1000012` (around 1MB)
Ended up increasing the kafka flag and all works well.

Cheers
