### ISSUE TITLE
Backwards incompatible change, "Producer.Return.Successes must be true to be used in a SyncProducer"

### ISSUE THREAD

**Issue by arnaud-lb** [Shopify/sarama#816]
Hi

The commit f0062da5ae1a62f7841e563a244e11a5ad9b96d7 / PR #790 introduces a backwards incompatible change: it is now required to set Producer.Return.Successes=true in a SyncProducer's config.

This breaks code that worked before. This breaks the following statement from the README:

> You can import a version with a guaranteed stable API via http://gopkg.in/Shopify/sarama.v1.

On a side note, this project is awesome, thank you for that :)

**Comment by eapache** [comment]
> On a side note, this project is awesome, thank you for that :)

You're welcome :)

> The commit f0062da / PR #790 introduces a backwards incompatible change: it is now required to set Producer.Return.Successes=true in a SyncProducer's config.
>
> This breaks code that worked before.

Hmm, you're right, I didn't consider that. I am too used to thinking of API stability as strictly a compile-time guarantee and so (since this doesn't prevent old code from compiling) it didn't occur to me.

There are two mitigating factors though:
- the previous behaviour was unquestionably broken (#789)
- the required update to new code is very minor (just setting one config value as you noted)

Given the nature of the bug, the simplicity of the required update, and the fact that (for better or worse) it's been part of a release for over a month now, I've decided to leave it as is.

I will put a warning in the CHANGELOG to this effect for anybody else who is updating.
