### ISSUE TITLE
Consumer Group Protocol type errors between implementations

### ISSUE THREAD

**Issue by joaodlf** [Shopify/sarama#832]
##### Versions
Sarama Version: 1.11.0
Kafka Version: 0.10.1.0
Go Version: 1.7.5

##### Configuration
(Note: We also use Sarama-Cluster, sc variable stands for that:)
```
kconf := sc.NewConfig()
kconf.Consumer.Return.Errors = true
kconf.Group.Return.Notifications = true
kconf.Consumer.Offsets.Initial = sarama.OffsetOldest
...
// Create consumer
consumer, err := sc.NewConsumer(brokersSlice, "test", topics, kconf)
```

This might be a long shot, but any help on this would be welcome. The issue is explained here:
https://github.com/Parsely/pykafka/issues/655

Essentially we are migrating some our processing to Go (from Python), but we still need to consume in the two implementations at the same time - And we would prefer to do this on the same consumer group. (This issue does not occur if we use different consumer groups)

If a PyKafka consumer(s) is already running and we start a Sarama consumer, these are the notifications we get:
```
INFO[2017-02-15 10:34:32] kafka server: The provider group protocol type is incompatible with the other members.
INFO[2017-02-15 10:34:32] Consumer Error: kafka server: The provider group protocol type is incompatible with the other members.
```

As explained in the PyKafka issue, the same thing happens the other way around (Sarama consumer running -> PyKafka consumer started)

We have spent some time in the client documentation for Kafka, but it's a bit outside our scope.

**Comment by joaodlf** [comment]
Correction, we are running Kafka 0.10.1.0.

**Comment by eapache** [comment]
So this is really a question better asked of the sarama-cluster folks, the balancing and consumer group logic is handled there. That said, I believe I know what the problem is.

Both pykafka and sarama-cluster use the "consumer" protocol type (https://github.com/bsm/sarama-cluster/blob/df980564b667f0249fd942d84b85f34274edb307/consumer.go#L544 and https://github.com/Parsely/pykafka/blob/5345019ef3a66c1c93d0c05f4d3504045324e5c6/pykafka/protocol.py#L1256) however they support a completely disjoint set of actual partition-assignment strategies.

Sarama-cluster supports the "range" and "roundrobin" protocols: https://github.com/bsm/sarama-cluster/blob/2c95218b78b369ef6cefbb2fd81d95af9960bd78/cluster.go#L11-L23 as defined by the reference java consumer.

Pykafka, as far as I can tell, supports only their own "pykafkaassignmentstrategy": https://github.com/Parsely/pykafka/blob/5345019ef3a66c1c93d0c05f4d3504045324e5c6/pykafka/protocol.py#L1256. cc @emmett9001 am I misreading, or is there a reason pykafka doesn't support any of the standard assignment strategies?

**Comment by emmett9001** [comment]
@eapache See https://github.com/Parsely/pykafka/issues/655#issuecomment-281829141 , I believe this lack of standard strategy support is simply a result of unclear documentation and a lack of comprehensive updates to pykafka around 0.10.

**Comment by eapache** [comment]
Makes sense to me, and I believe you are correct that the `range` strategy is identical to the old-style balancing algorithm.

Any further questions about this on the golang side should probably be directed to the sarama-cluster repository.
