### ISSUE TITLE
Broker read channel returning nil?

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#833]
I am not able to reproduce this reliably and find the pattern behind the problem so not filing this as a bug, but I am occasionally getting a nil message returned by the `PartitionConsumer.Messages()` channel.

Can we think of any possible causes for this?

**Comment by eapache** [comment]
Sarama will never put a nil message on the channel. If you are getting nils then the channel has probably been closed (a receive from a closed channel returns the zero value for that type, which is nil for pointers).

The channel will normally be closed only when the PartitionConsumer has been shut down, either by calling `Close` or `AsyncClose` on it.

The PartitionConsumer may sometimes shut itself down when it encounters an unrecoverable error; in this case you will get an appropriate error on the `Errors` channel, and it will also log a message to `Sarama.Logger` that looks something like: `consumer/TOPIC/PARTITION shutting down because REASON`

**Comment by kchristidis** [comment]
This was quite helpful, thank you.

Using the `sarama.logger` output, I found out I'm dealing with a request offset that is out of range.
