### ISSUE TITLE
Question: Does consuming partitions "stops" on a kafka log roll?

### ISSUE THREAD

**Issue by wyndhblb** [Shopify/sarama#844]
Sarama Version: gitsha: 1416bd78f804d523005322194994f08c2a0ad797
Kafka Version: 0.10.2
Go Version: 1.8

This is more a question then an issue, as the issue may lie in kafka itself

The scenario:
- kafka topic is "full" (i.e. it has data going back to the `log.retention.hours` setting)
- Single Partition consumer for each partition
- Start consuming at OffsetOldest :: each partition tend to get ~4-5k msg/sec
- consumption starts at levels higher then production (in my test case ~10-15k/s)
- at some point kafka "rolls" the old log file (i.e. INFO Rolled new log segment for 'topic-{partition}')
- the consumer was not "done" consuming that log segment
- consumption rates drop to "0" on the rolled partition 
- no errors are mentioned, and things tick on as normal, but nothing is consumed anymore.

So the question: is this "normal"? could this be an issue w/ kafka itself? or is there some way to mitigate this sort of behavior?

Another potential issue might be some sort of race condition between when `consumer, err := client.ConsumePartition(topic, partition, sarama.OffsetOldest)` is called and when the consumption actually starts (i.e. when `consumer.Messages()` is called) in that the initial 'OffsetOldest' obtained in the  is no longer really the oldest.

**Comment by eapache** [comment]
I believe this is similar/related to https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#why-am-i-getting-a-nil-message-from-the-sarama-consumer

Here's what *should* happen when a log segment gets rolled while it is still being consumed:
- kafka sends the consumer an `OffsetOutOfRange` error
- the consumer logs this error (to `sarama.Logger`) and returns it as an error on the `Errors()` channel
- the consumer stops consuming this partition; at this point it's up to the calling program to decide if it just wants to restart at the new `OffsetOldest`, or raise a more serious error for a human being to look at

It sounds like the consumer is stopping correctly since nothing is consumed anymore, but you're not getting any errors. Are you reading from the `Errors()` channel? Perhaps you have disabled it via the `Consumer.Return.Errors` config value? Have you enabled logging by setting `sarama.Logger`?

If everything looks correct and you're *still* not getting any notification, please provide additional debugging information (e.g. whatever logs you *are* getting, that sort of thing).

**Comment by wyndhblb** [comment]
Hi, yes i do have the err channel ticking (so as to log when things get wedged (or if they do) when there is an Leader/ISR change, and see those messages just fine)

**Comment by wyndhblb** [comment]
Also isn't the `sarama.ErrOffsetOutOfRange` not a "consumer Error" (it's a `KError`)? Would that error appear through the `consumer.Error()` channel?  

I do see that error when i do a `client.ConsumePartition(topic, partition, NonsenseOffsetNumber)`

**Comment by wyndhblb** [comment]
Yep.  Saw the warning about ErrOffsetOutOfRange  in my logs when kafka rotated the earliest log file out (took a while to catch it).  Thanks for the help.

**Comment by eapache** [comment]
You're welcome.
