### ISSUE TITLE
Take error when get all group from client

### ISSUE THREAD

**Issue by tfzxyinhao** [Shopify/sarama#853]
##### Versions

Sarama Version:1.11.0
Kafka Version: 2.11
Go Version:go1.8 windows/amd64

##### Configuration

config := sarama.NewConfig()

##### Logs

kafka: broker not connected

##### Problem Description

```
for _, item := range client.Brokers() {
    var req sarama.ListGroupsRequest
    resp, err := item.ListGroups(&req)
     if err != nil {
	log.Println(err)
    } 
}
```

**Comment by eapache** [comment]
Oh, hmm, this is because we don't automatically open connections to brokers as returned from the new `Brokers()` method (#813). If they haven't already been talked to for some other reason you'll get this error. @hollow I'm kind of surprised you haven't run into this.

As a short-term workaround, just call `Open()` on each broker before calling `ListGroups` (and ignore any `ErrAlreadyConnected`). In the longer term we should probably either open all the brokers before we return them or at least document this behaviour.
