### ISSUE TITLE
Handle reconnection to coordinator broker

### ISSUE THREAD

**Issue by sebgl** [Shopify/sarama#866]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 574d3147eee384229bf96a5d12c207fe7b5234f3
Kafka Version: 0.10.1.1
Go Version: 1.7

##### Configuration

config.Net.KeepAlive = 2 * time.Second
Otherwise, pretty much default configuration. Note that the problem happens both on TLS+SASL connection and direct connection.

##### Logs

Error on broker.FetchOffset(request) - raised forever after the first time:

> time="2017-03-30T20:38:09Z" level=error error="write tcp 172.17.0.2:60842->brokerip:9092: write: broken pipe"

Sarama logs before the error above (nothing particular):

> 2017/03/30 20:38:09 client/coordinator coordinator for consumergroup myconsumergroup is #3 (myurl:9092)
> 2017/03/30 20:38:09 client/coordinator requesting coordinator for consumergroup myconsumergroup from brokerip:9092
> 2017/03/30 20:38:09 client/metadata fetching metadata for [mytopic] from broker brokerip:9092

##### Problem Description

I'm regularly (every 30sec) polling Kafka with a FetchOffsetRequest that I manually build, to retrieve my topic's offsets, for monitoring purpose, using the same sarama client as my producer and consumer. It works very well.

However, from time to time the FetchOffsetRequest fails with a "write tcp 172.17.0.2:60842->brokerip:9092: write: broken pipe" error. Starting this point, the FetchOffsetRequest which I perform every 30 sec will always fail with the same error.
Something interesting I noticed: the local port in the error message (60842 on the log above) is always the same for all error logs I get after the first one. Somehow I would expect that this local port would change after the first error (tcp reconnection?).

Below is the code that gets executed every 30sec:

```
	err := h.saramaClient.RefreshMetadata(h.config.Topic)
	if err != nil {
		log.WithError(err).Error("Fail to refresh metadata")
		return
	}
	partitions, err := h.saramaClient.Partitions(h.config.Topic)
	if err != nil {
		log.WithError(err).Errorf("Fail to retrieve partitions for topic %s", h.config.Topic)
		return
	}
	if len(partitions) == 0 {
		log.Errorf("We got 0 partitions for topic %s", h.config.Topic)
		return
	}
	err = h.saramaClient.RefreshCoordinator(h.config.ConsumerGroupID)
	if err != nil {
		log.WithError(err).Errorf("Fail to refresh coordinator for consumer group %s", h.config.ConsumerGroupID)
		return
	}

	// retrieve consumer group coordinator
	broker, err := h.saramaClient.Coordinator(h.config.ConsumerGroupID)
	if err != nil {
		log.WithError(err).Errorf("Fail to get consumer group coordinator for %s", h.config.ConsumerGroupID)
		return
	}

	// build OffsetFetchRequest with a block for each partition
	request := new(sarama.OffsetFetchRequest)
	request.Version = 1
	request.ConsumerGroup = h.config.ConsumerGroupID
	for _, p := range partitions {
		request.AddPartition(h.config.Topic, p)
	}
	response, err := broker.FetchOffset(request)
	if err != nil {
		log.WithError(err).Errorf("Fail to perform OffsetFetchRequest for topic %s", h.config.Topic)
        }

```
This last error is the one that raises forever after the first occurence.

A workaround for this problem that I'm using right now is to manually call broker.Close() and broker.Open() on the broker I got from client.Coordinator(), before the call to broker.FetchOffset().

Maybe that's just normal behaviour and I must handle reconnection myself? Note that I do not have any reconnection problem in my producer & consumer code.

**Comment by wvanbergen** [comment]
The broker objects usually don't manage their connection; we do that in the Client object. We do this because in many cases we prefer asking a different broker rather asking the same broker again. 

E.g. [Client closes the connection after an error](https://github.com/Shopify/sarama/blob/master/client.go#L542-L546), which causes us to re-start the connection if that broker instance gets used again.

Unfortunately we don't really have a high level API to fetch the offset for a consumergroup on Client (yet), but we do use these APIs in our high level [OffsetManager](https://github.com/Shopify/sarama/blob/master/offset_manager.go). But I don't think the OffsetManager is really what you're looking for for your use case.

The simplest solution for your example would be to `Close()` the `Broker` in case you see an error, and always call `Open()` before using it. Or better, every time you see an error, assume the Broker is down, and the coordinator may have changed, and call `RefreshCoordinator()`.

**Comment by sebgl** [comment]
Thanks for your quick and detailed answer. It makes sense, I'll do what you suggest in the error case. I consider this issue solved :)

**Comment by wvanbergen** [comment]
Cool, in the future we may want to add higher level APIs for this use case, but for now the workaround will have to do/
