### ISSUE TITLE
The right way to use SyncProducer?

### ISSUE THREAD

**Issue by JodeZer** [Shopify/sarama#876]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:0fb560e5f7fbcaee2f (v1.11)
Kafka Version:0.10.1.0
Go Version:1.6.3

##### Problem Description

Hi, l used to test on sarama for days. And l got confused on usage of SyncProducer.

The write performance is big problem. l worder what situation can SyncProducer be used?l think AsyncProducer with return sussess is a much better choice .

**Comment by wvanbergen** [comment]
The SyncProducer is inherently slower, because for every message you produce, it will block until it has gotten confirmation that the message has been successfully produced to the cluster.

You use it if your use case depends on that, e.g. you want to wait doing any further processing until you're sure that your message has been successfully produced. If you can get your use case to work with the async producer, you will normally see much higher performance, but often requires more complex code. With the sync producer, you can get much higher throughput if you can parallelize your workload.
