### ISSUE TITLE
Excuse me,When I reboot my consumer,I cat get the kafka message which remain in kafka,What can I do to maintain the message's offset?

### ISSUE THREAD

**Issue by Anteoy** [Shopify/sarama#879]
##### Versions

Sarama Version: 1.12.0
Kafka Version: docker hub 
Go Version: 1.7

##### Configuration

config := sarama.NewConfig()
config.Producer.Return.Successes = true

##### Problem Description

Excuse me,When I reboot my consumer,I cat get the kafka message which remain in kafka,What can I do to maintain the message's offset? This is the first time I have used kafka,Also please see understanding。

**Comment by Anteoy** [comment]
`partitionConsumer, err := consumer.ConsumePartition("datacenter", 0, sarama.OffsetNewest)
	if err != nil {
		panic(err)
	}`
This is my consumer code.

**Comment by wvanbergen** [comment]
You basically have to store the last offset you have consumed for every topic/partition somewhere, and use that to resume where you left off when you restart. In your example, you'd use the third  parameter rather than `OffsetNewest`.

You may be interested in a high-level consumer which manages this for you. See https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#consuming for more info.

**Comment by Anteoy** [comment]
It worked for me!Thank you
