### ISSUE TITLE
Kafka consumer takes long time to receive message

### ISSUE THREAD

**Issue by male110** [Shopify/sarama#946]
From producer sending messages to consumers receiving messages for more than 1 second, the delay is long.why?

**Comment by eapache** [comment]
I do not have nearly enough information to be able to answer this question. 1 second is not an unreasonable total time from producer to consumer since there are at least two complete network round-trips in that flow and possibly more depending on replication.

What version of Sarama (and Kafka) are you using? What configuration values? Can you provide logs?

**Comment by male110** [comment]
you can close it,thanks.
