### ISSUE TITLE
Unable to join a consumer group with the same client

### ISSUE THREAD

**Issue by dim** [Shopify/sarama#958]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.9

##### Problem Description

Hi, I am the author of https://github.com/bsm/sarama-cluster and recently received a bug ticket about users being unable to run multiple consumer instances while (re-)using the connections of the  same underlying `sarama.Client` instance. After some debugging, I noticed that it's impossible to call `broker.JoinGroup` concurrently from multiple goroutines (when the client is shared). 

Here's a short pseudo-code example (full example below).

#### this works!

```go
func consume() {
  client, _ := sarama.NewClient([]string{"127.0.0.1:9092"}, nil)
  defer client.Close()
  broker, _ := client.Coordinator("my-group")
  broker.JoinGroup(&sarama.JoinGroupRequest{...})
}
func main() {
  go consume()
  go consume()
  time.Sleep(time.Hour)
}
```

#### this doesn't!

```go
func consume(client sarama.Client) {
  broker, _ := client.Coordinator("my-group")
  broker.JoinGroup(&sarama.JoinGroupRequest{...})
}
func main() {
  client, _ := sarama.NewClient([]string{"127.0.0.1:9092"}, nil)
  defer client.Close()

  go consume(client)
  go consume(client)
  time.Sleep(time.Hour)
}
```

When I run my example (see below), one of the consumers hangs until the other times out. I tried to hack sarama and vary the broker's `correlationID` but that didn't work either. Kafka seems to be actively blocking the broker connection which means that I need a dedicated broker connection per consumer to make this work but I am unable to obtain multiple `Broker` instances through the existing `client.Coordinator` API. Any hints/ideas on what I can do?

The full code:

```
package main

import (
	"context"
	"log"

	"github.com/Shopify/sarama"
	"golang.org/x/sync/errgroup"
)

const groupID = "my-group"

func main() {
	if err := run(); err != nil {
		log.Fatalln(err)
	}
}

func run() error {
	config := sarama.NewConfig()
	config.Version = sarama.V0_10_0_0

	client, err := sarama.NewClient([]string{"127.0.0.1:9092"}, config)
	if err != nil {
		return err
	}
	defer client.Close()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	eg, _ := errgroup.WithContext(ctx)
	eg.Go(func() error { return joinGroup("A", client) })
	eg.Go(func() error { return joinGroup("B", client) })
	return eg.Wait()
}

func joinGroup(name string, client sarama.Client) error {
	req := &sarama.JoinGroupRequest{
		GroupId:        groupID,
		SessionTimeout: 7 * 1000,
		ProtocolType:   "consumer",
	}
	if err := req.AddGroupProtocolMetadata("range", &sarama.ConsumerGroupMemberMetadata{
		Version: 1,
		Topics:  []string{"topic-a"},
	}); err != nil {
		return err
	}

	broker, err := client.Coordinator(groupID)
	if err != nil {
		return err
	}

	resp, err := broker.JoinGroup(req)
	if err != nil {
		return err
	} else if resp.Err != sarama.ErrNoError {
		return resp.Err
	}

	role := "follower"
	if resp.MemberId == resp.LeaderId {
		role = "leader"
	}
	log.Printf("Consumer %q joined group %q as %s/%d (as %s, %d members)", name, groupID, resp.MemberId, resp.GenerationId, role, len(resp.Members))
	return nil
}
```

The output is:

```
2017/09/26 13:19:38 Consumer "B" joined group "my-group" as sarama-269af852-e5a8-4521-a902-ac46f1972a61/10 (as leader, 1 members)
2017/09/26 13:19:45 Consumer "A" joined group "my-group" as sarama-1c10fcbe-acda-474b-ba5e-8296f3ea3b92/11 (as leader, 1 members)
```

**Comment by eapache** [comment]
> Hi, I am the author of https://github.com/bsm/sarama-cluster

I know who you are :)

> When I run my example (see below), one of the consumers hangs until the other times out.

Kafka processes requests on a single connection in a strictly serial fashion; until the first message has been processed, the second will not be considered. See https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Network. Given this, it isn't surprising that the second `JoinGroupRequest` ends up waiting on the first when using only a single connection.

What *is* surprising to me is that the first `JoinGroupRequest` takes more than a few-hundred milliseconds to complete, based on my reading of the spec there's no blocking or slow processing involved there. I wouldn't have expected it to cause this kind of problem.

> I am unable to obtain multiple Broker instances through the existing client.Coordinator API

That is for simplicity since in general you should never need multiple connections to the same broker. You can manually clone a broker if you have to by calling `NewBroker(oldBroker.Addr())`; it won't have the right broker-ID and thus might confuse some metrics but it should get you a second TCP connection.

> unable to run multiple consumer instances while (re-)using the connections of the same underlying sarama.Client instance

I'm not super-familiar with sarama-cluster's capabilities in this respect, but Kafka's networking behaviour makes this a tricky proposition, as you've discovered. It is currently impractical to run multiple pure-sarama consumers or producers off of a single client because they will fight over the broker connection in this fashion (particularly consumers on low-volume topics when the request/response cycle can be slow if there are insufficient messages). This isn't really a problem because a single producer or consumer can handle arbitrary topic/partitions so there's usually never a need to have multiple instances.

**Comment by dim** [comment]
Hmm, that's what I thought, thanks for clarifying.
